=== owng25/arena-gauntlet-personal/json_data_copy/schemas/AugmentData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Augment Data",
	"$ref": "#/$defs/AugmentType",
	"$defs": {
		"AugmentType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"ActivationTrigger": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatActivationTriggerData"
				},
				"Name": {
					"type": "string"
				},
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"Type": {
					"$ref": "#/$defs/AugmentTypeEnum"
				},
				"CombatClasses": {
					"additionalProperties": {
						"type": "integer"
					}
				},
				"CombatAffinities": {
					"additionalProperties": {
						"type": "integer"
					}
				}
			},
			"additionalProperties": false
		},
		"AugmentTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Component", "GreaterPower", "SynergyBonus"]
		},
		"AugmentTypeID": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Legendary/SappingHex_Original.json
{
	"Name": "SappingHex",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "GreaterPower",
	"Abilities": [
		{
			"Name": "Sapping Hex Ability",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 1000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Sapping Hex - Debuffs",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "InZone",
						"Group": "Enemy",
						"RadiusUnits": 25
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Debuff",
								"Stat": "OmegaPowerPercentage",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"Expression": 3
							},
							{
								"Type": "Debuff",
								"Stat": "EnergyResist",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"Expression": 3
							},
							{
								"Type": "Debuff",
								"Stat": "PhysicalResist",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"Expression": 3
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Sapping Hex",
	"DisplayDescription": "Enemies within 25-hexes lose 3 <OmegaPowerPercentage>Omega Power</> and <Resistance>Resistances</> per second.",
	"Description": {
		"Format": "Enemies within {Radius}-hexes lose {DebuffVal} <OmegaPowerPercentage>Omega Power</> and <Resistance>Resistances</> per second.",
		"Parameters": {
			"Radius": {
				"ParameterPath": "Abilities[0].Skills[0].Targeting.RadiusUnits",
				"ValueMultiplier": 1.0
			},
			"DebuffVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[2].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Enemies within 25-hexes lose 3 Omega Power and Resistances per second."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Legendary/SuccorsGift_Original.json
{
	"Name": "SuccorsGift",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "GreaterPower",
	"Abilities": [
		{
			"Name": "SuccorsGift_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "SuccorsGift - Vulnerability",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Aura",
								"AttachedEffects": [
									{
										"Type": "Buff",
										"Stat": "VulnerabilityPercentage",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 25,
										"Expression": 15
									},
									{
										"Type": "Buff",
										"Stat": "AttackPhysicalDamage",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 25,
										"Expression": {
											"Percentage": 15,
											"Stat": "AttackPhysicalDamage",
											"StatSource": "Receiver"
										}
									},
									{
										"Type": "Buff",
										"Stat": "AttackEnergyDamage",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 25,
										"Expression": {
											"Percentage": 15,
											"Stat": "AttackEnergyDamage",
											"StatSource": "Receiver"
										}
									},
									{
										"Type": "Buff",
										"Stat": "AttackPureDamage",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 25,
										"Expression": {
											"Percentage": 15,
											"Stat": "AttackPureDamage",
											"StatSource": "Receiver"
										}
									},
									{
										"Type": "Buff",
										"Stat": "OmegaDamagePercentage",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 25,
										"Expression": {
											"Percentage": 15,
											"Stat": "OmegaDamagePercentage",
											"StatSource": "Receiver"
										}
									}
								]
							}
						]
					}
				}
			]
		},
		{
			"Name": "SuccorsGift_Ability2",
			"ActivationTrigger": {
				"TriggerType": "HealthInRange",
				"HealthLowerLimitPercentage": 20,
				"MaxActivations": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "SuccorsGift - Indomitable",
					"Targeting": {
						"Type": "ExpressionCheck",
						"Guidance": [
							"Ground",
							"Airborne",
							"Underground"
						],
						"Group": "Ally",
						"Lowest": true,
						"Num": 3,
						"Expression": {
							"Stat": "CurrentHealth%",
							"StatSource": "Sender"
						}
					},
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "PositiveState",
								"PositiveState": "Indomitable",
								"DurationMs": 3000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Succors Gift",
	"DisplayDescription": "The holder and allies within 25-hexes gain <DamageReduction>15%</> <DamageReduction>Damage Reduction</> and <DamageAmplification>15%</> <DamageAmplification>Damage Amp</>.\r\n\r\nOnce per combat, at 20% Health, the holder grants Indomitable to the 3 lowest percent Health allies for 3 seconds.\r\n\r\n<Italic>Indomitable: Cannot drop below 1 Health.</>",
	"Description": {
		"Format": "The holder and allies within {Radius}-hexes gain <DamageReduction>{DmgRedVal}%</> <DamageReduction>Damage Reduction</> and <DamageAmplification>{DmgRedVal}%</> <DamageAmplification>Damage Amp</>.\r\n\r\nOnce per combat, at {HealthTrigger}% Health, the holder grants Indomitable to the {AllyNum} lowest percent Health allies for {Duration} seconds.\r\n\r\n<Italic>Indomitable: Cannot drop below 1 Health.</>",
		"Parameters": {
			"Radius": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].RadiusUnits",
				"ValueMultiplier": 1.0
			},
			"DmgRedVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].Expression"
			},
			"HealthTrigger": {
				"ParameterPath": "Abilities[1].ActivationTrigger.HealthLowerLimitPercentage",
				"ValueMultiplier": 1.0
			},
			"AllyNum": {
				"ParameterPath": "Abilities[1].Skills[0].Targeting.Num",
				"ValueMultiplier": 1.0
			},
			"Duration": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "The holder and allies within 25-hexes gain 15% Damage Reduction and 15% Damage Amp.\r\n\r\nOnce per combat, at 20% Health, the holder grants Indomitable to the 3 lowest percent Health allies for 3 seconds.\r\n\r\nIndomitable: Cannot drop below 1 Health."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Synergy/CompositeImprint_Verdant.json
{
	"Name": "Verdant",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "SynergyBonus",
	"CombatAffinities": {
		"Verdant": 1
	},
	"Abilities": [
		{
			"Name": "Verdant Imprint Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Verdant Imprint Stat List",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 200000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Verdant Affinity Chip",
	"DisplayDescription": "The holder gains the Verdant Composite Affinity and 200 <MaxHealth>Max Health</>.",
	"Description": {
		"Format": "The holder gains the Verdant Composite Affinity and 200 <MaxHealth>Max Health</>.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The holder gains the Verdant Composite Affinity and 200 Max Health."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Synergy/BaseImprint_Nature.json
{
	"Name": "Nature",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "SynergyBonus",
	"CombatAffinities": {
		"Nature": 1
	},
	"Abilities": [
		{
			"Name": "Nature Imprint Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Nature Imprint Stat List",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 100000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Nature Imprint",
	"DisplayDescription": "The holder gains the Nature Affinity and 100 <MaxHealth>Max Health</>.",
	"Description": {
		"Format": "The holder gains the Nature Affinity and 100 <MaxHealth>Max Health</>.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The holder gains the Nature Affinity and 100 Max Health."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Legendary/ReactiveTransference_Original.json
{
	"Name": "ReactiveTransference",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "GreaterPower",
	"Abilities": [
		{
			"Name": "ReactiveTransference_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnHit",
				"SenderAllegiance": "Enemy",
				"ReceiverAllegiance": "Self",
				"AbilityTypes": [
					"Attack"
				],
				"ActivationCooldownMs": 1000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "ReactiveTransference - Buffs",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 5,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 5,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 5,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		},
		{
			"Name": "ReactiveTransference_Ability2",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "ReactiveTransference - Attack Damage Bonus",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 50,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Reactive Transference",
	"DisplayDescription": "The holder gains <AttackDamage>50%</> <AttackDamage>Attack Damage</> and after being hit by an attack gain bonus <AttackDamage>5%</> <AttackDamage>Attack Damage</>. (1s cooldown)",
	"Description": {
		"Format": "The holder gains <AttackDamage>{ADVal2}%</> <AttackDamage>Attack Damage</> and after being hit by an attack gain bonus <AttackDamage>{ADVal}%</> <AttackDamage>Attack Damage</>. ({Cooldown}s cooldown)",
		"Parameters": {
			"ADVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"Cooldown": {
				"ParameterPath": "Abilities[0].ActivationTrigger.ActivationCooldownMs",
				"ValueMultiplier": 0.001
			},
			"ADVal2": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "The holder gains 50% Attack Damage and after being hit by an attack gain bonus 5% Attack Damage. (1s cooldown)"
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Synergy/CompositeImprint_Predator.json
{
	"Name": "Predator",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "SynergyBonus",
	"CombatClasses": {
		"Predator": 1
	},
	"Abilities": [
		{
			"Name": "Predator Imprint Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Predator Imprint Stat List",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Predator Imprint",
	"DisplayDescription": "The holder gains the Predator Composite Class and 20% <AttackDamage>Attack Damage</>.",
	"Description": {
		"Format": "The holder gains the Predator Composite Class and 20% <AttackDamage>Attack Damage</>.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The holder gains the Predator Composite Class and 20% Attack Damage."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Legendary/OmnisourceSurge_Original.json
{
	"Name": "OmnisourceSurge",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "GreaterPower",
	"Abilities": [
		{
			"Name": "OmnisourceSurge_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "OmnisourceSurge - Start Buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"Expression": 30
							}
						]
					}
				}
			]
		},
		{
			"Name": "OmnisourceSurge_Ability2",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 4000,
				"MaxActivations": 8
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "OmnisourceSurge - Omega Buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"Expression": 10
							},
							{
								"Type": "Buff",
								"Stat": "EnergyPiercingPercentage",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"Expression": 10
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Omnisource Surge",
	"DisplayDescription": "Gain <OmegaPowerPercentage>30</> <OmegaPowerPercentage>Omega Power</>. Every 4 seconds, gain an additional <OmegaPowerPercentage>10</>  <OmegaPowerPercentage>Omega Power</> and <EnergyPiercingPercentage>10%</> <EnergyPiercingPercentage>Energy Resist Piercing</>, up to 8 stacks.",
	"Description": {
		"Format": "Gain <OmegaPowerPercentage>{InitialOP}</> <OmegaPowerPercentage>Omega Power</>. Every {TriggerTime} seconds, gain an additional <OmegaPowerPercentage>{StackOP}</>  <OmegaPowerPercentage>Omega Power</> and <EnergyPiercingPercentage>{EngPierce}%</> <EnergyPiercingPercentage>Energy Resist Piercing</>, up to {Stacks} stacks.",
		"Parameters": {
			"InitialOP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"TriggerTime": {
				"ParameterPath": "Abilities[1].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			},
			"StackOP": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"EngPierce": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[1].Expression",
				"ValueMultiplier": 1.0
			},
			"Stacks": {
				"ParameterPath": "Abilities[1].ActivationTrigger.MaxActivations",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Gain 30 Omega Power. Every 4 seconds, gain an additional 10  Omega Power and 10% Energy Resist Piercing, up to 8 stacks."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Legendary/RuinationPrism_Original.json
{
	"Name": "RuinationPrism",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "GreaterPower",
	"Abilities": [
		{
			"Name": "RuinationPrism_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Physical resist and grit debuff aura",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "OmegaDamagePercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 20,
									"Stat": "OmegaDamagePercentage",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		},
		{
			"Name": "RuinationPrism_Ability2",
			"ActivationTrigger": {
				"TriggerType": "OnHit",
				"AbilityTypes": [
					"Attack"
				],
				"SenderAllegiance": "Self",
				"ReceiverAllegiance": "Enemy",
				"EveryX": true
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "RuinationPrism - Self Buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Operation": "*",
									"Operands": [
										{
											"Percentage": 5,
											"Stat": "PhysicalResist",
											"StatSource": "SenderFocus"
										}
									]
								}
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Operation": "*",
									"Operands": [
										{
											"Percentage": 5,
											"Stat": "EnergyResist",
											"StatSource": "SenderFocus"
										}
									]
								}
							}
						]
					}
				},
				{
					"Name": "RuinationPrism - Enemy Debuff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Debuff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 5,
									"Stat": "PhysicalResist",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Debuff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 5,
									"Stat": "EnergyResist",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Ruination Prism",
	"DisplayDescription": "Gain <DamageAmplification>20%</> <DamageAmplification>Damage Amp</>. Holder's attacks steal <Resistance>5%</> <Resistance>Resistances</> from the target.",
	"Description": {
		"Format": "Gain <DamageAmplification>{DmgAmp}%</> <DamageAmplification>Damage Amp</>. Holder's attacks steal <Resistance>{ResistSteal}%</> <Resistance>Resistances</> from the target.",
		"Parameters": {
			"DmgAmp": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"ResistSteal": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression.Operands[0].Percentage",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Gain 20% Damage Amp. Holder's attacks steal 5% Resistances from the target."
}
