=== owng25/arena-gauntlet-personal/json_data_copy/schemas/AugmentData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Augment Data",
	"$ref": "#/$defs/AugmentType",
	"$defs": {
		"AugmentType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"ActivationTrigger": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatActivationTriggerData"
				},
				"Name": {
					"type": "string"
				},
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"Type": {
					"$ref": "#/$defs/AugmentTypeEnum"
				},
				"CombatClasses": {
					"additionalProperties": {
						"type": "integer"
					}
				},
				"CombatAffinities": {
					"additionalProperties": {
						"type": "integer"
					}
				}
			},
			"additionalProperties": false
		},
		"AugmentTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Component", "GreaterPower", "SynergyBonus"]
		},
		"AugmentTypeID": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Legendary/AdaptiveReflection_Original.json
{
	"Name": "AdaptiveReflection",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "GreaterPower",
	"Abilities": [
		{
			"Name": "AdaptiveReflection_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnDamage",
				"SenderAllegiance": "Enemy",
				"ReceiverAllegiance": "Self",
				"AbilityTypes": [
					"Attack",
					"Omega"
				]
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "AdaptiveReflection - Gain Resistances",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"MaxStacks": 40,
								"Expression": 2
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"DurationMs": -1,
								"OverlapProcessType": "Stacking",
								"MaxStacks": 40,
								"Expression": 2
							}
						]
					}
				}
			]
		},
		{
			"Name": "AdaptiveReflection_Ability2",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 2000,
				"NotBeforeMs": 12000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "AdaptiveReflection - AOE Damage",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "InZone",
						"Group": "Enemy",
						"RadiusUnits": 20
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Operation": "*",
									"Operands": [
										40,
										{
											"Operation": "+",
											"Operands": [
												{
													"Stat": "PhysicalResist",
													"StatSource": "Sender"
												},
												{
													"Stat": "EnergyResist",
													"StatSource": "Sender"
												}
											]
										},
										10
									]
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Adaptive Reflection",
	"DisplayDescription": "Gain <Resistance>2</> <Resistance>Resistances</> when taking damage, up to 40 stacks.\r\n\r\nAfter 12 seconds, deal <Resistance>40%</> of holder's combined <Resistance>Resistances</> as Pure Damage within 20-hexes every 2 seconds.",
	"Description": {
		"Format": "Gain <Resistance>{ResistVal}</> <Resistance>Resistances</> when taking damage, up to {Stacks} stacks.\r\n\r\nAfter {TriggerTime} seconds, deal <Resistance>{Damage}%</> of holder's combined <Resistance>Resistances</> as Pure Damage within {Radius}-hexes every {DamageTrigger} seconds.",
		"Parameters": {
			"ResistVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stacks": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].MaxStacks",
				"ValueMultiplier": 1.0
			},
			"TriggerTime": {
				"ParameterPath": "Abilities[1].ActivationTrigger.NotBeforeMs",
				"ValueMultiplier": 0.001
			},
			"Damage": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression.Operands[0]",
				"ValueMultiplier": 1.0
			},
			"Radius": {
				"ParameterPath": "Abilities[1].Skills[0].Targeting.RadiusUnits",
				"ValueMultiplier": 1.0
			},
			"DamageTrigger": {
				"ParameterPath": "Abilities[1].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "Gain 2 Resistances when taking damage, up to 40 stacks.\r\n\r\nAfter 12 seconds, deal 40% of holder's combined Resistances as Pure Damage within 20-hexes every 2 seconds."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Synergy/CompositeImprint_Mystic.json
{
	"Name": "Mystic",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "SynergyBonus",
	"CombatClasses": {
		"Mystic": 1
	},
	"Abilities": [
		{
			"Name": "Mystic Imprint Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Mystic Imprint Stat List",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"DurationMs": -1,
								"Expression": 200000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Mystic Imprint",
	"DisplayDescription": "The holder gains the Mystic Composite Class and 200 <MaxHealth>Max Health</>.",
	"Description": {
		"Format": "The holder gains the Mystic Composite Class and 200 <MaxHealth>Max Health</>.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The holder gains the Mystic Composite Class and 200 Max Health."
}
