=== owng25/arena-gauntlet-personal/json_data_copy/schemas/ConsumableData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Augment Data",
	"$ref": "#/$defs/ConsumableType",
	"$defs": {
		"ConsumableType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"IsDisabled": {
					"type": "boolean"
				}
			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/ConsumableData/BasketFruit_Stage3.json
{
	"Name": "BasketFruit",
	"Stage": 3,
	"Tier": 3,
	"Abilities": [
		{
			"Name": "Recover 4% MaxHealth per second.",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 1000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Instant heal",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantHeal",
								"HealType": "Normal",
								"Expression": {
									"Percentage": 5,
									"Stat": "MaxHealth",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	]
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/ConsumableData/JellyFruit_Stage0.json
{
	"Name": "JellyFruit",
	"Stage": 0,
	"Tier": 0,
	"Abilities": [
		{
			"Name": "Consumable - Jelly Fruit",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "OP and Energy Regen buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"DurationMs": -1,
								"Expression": 15
							},
							{
								"Type": "Buff",
								"Stat": "EnergyRegeneration",
								"Expression": 150,
								"DurationMs": -1
							}
						]
					}
				}
			]
		}
	]
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/ConsumableData/SpikeJuice_Stage3.json
{
	"Name": "SpikeJuice",
	"Stage": 3,
	"Tier": 3,
	"Abilities": [
		{
			"Name": "Gain Indomitable for 10 seconds.",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Indomitable",
					"Targeting": {
						"Type": "Self"
					},
					"Deployment": {
						"Type": "Direct"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "PhysicalVampPercentage",
								"DurationMs": -1,
								"Expression": 28
							},
							{
								"Type": "Buff",
								"Stat": "EnergyVampPercentage",
								"DurationMs": -1,
								"Expression": 28
							},
							{
								"Type": "Buff",
								"Stat": "PureVampPercentage",
								"DurationMs": -1,
								"Expression": 28
							}
						]
					}
				}
			]
		}
	]
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/ConsumableData/NaniticDiscord_Stage3.json
{
	"Name": "NaniticDiscord",
	"Stage": 3,
	"Tier": 3,
	"Abilities": [
		{
			"Name": "Debuff - Nanitic Discord",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Attack Speed debuff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackSpeed",
								"DurationMs": -1,
								"Expression": {
									"Percentage": -35,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		}
	]
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/ConsumableData/Floraball_Stage0.json
{
	"Name": "Floraball",
	"Stage": 0,
	"Tier": 0,
	"Abilities": [
		{
			"Name": "Consumable - Floraball",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Max Health and Energy/Physical Resist buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"Expression": 200000,
								"DurationMs": -1
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"Expression": 20,
								"DurationMs": -1
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"Expression": 20,
								"DurationMs": -1
							}
						]
					}
				}
			]
		}
	]
}
