=== owng25/arena-gauntlet-personal/json_data_copy/schemas/DroneAugmentData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Drone Augment Data",
	"$ref": "#/$defs/DroneAugmentType",
	"$defs": {
		"DroneAugmentType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Name": {
					"type": "string"
				},
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Stage": {
					"type": "integer"
				},
				"Type": {
					"$ref": "#/$defs/DroneAugmentTypeEnum"
				},
				"RuntimeBonus": {
					"$ref": "#/$defs/RuntimeBonusType"
				}
			},
			"additionalProperties": false
		},
		"DroneAugmentTypeEnum": {
			"type": "string",
			"enum": [ "Simulation", "Game", "ServerAndGame"]
		},
		"RuntimeBonusType": {
			"type": "object",
			"properties": {
				"GrantedAugments": {
					"type": "array",
					"items": {
						"$ref": "AugmentData.schema.json#/$defs/AugmentTypeID"
					}
				},
				"GrantedCredits": {
					"type": "integer"
				}

			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/SecondWind_Stage1.json
{
	"Name": "SecondWind",
	"Stage": 1,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "Second Wind 1 - Ability",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 20000,
				"MaxActivations": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Second Wind 1 - Heal",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Allegiance",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantHeal",
								"HealType": "Normal",
								"Expression": {
									"Percentage": 25,
									"Stat": "MaxHealth",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Second Wind I",
	"DisplayDescription": "20 seconds into the battle, your team heals for 25% of their Max Health.",
	"Description": {
		"Format": "{TriggerTime} seconds into the battle, your team heals for {HealValue}% of their Max Health.",
		"Parameters": {
			"TriggerTime": {
				"ParameterPath": "Abilities[0].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			},
			"HealValue": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/SmolderingStrike_Stage2.json
{
	"Name": "SmolderingStrike",
	"Stage": 2,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "SmolderingStrike_Buf",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Your Fire Units attacks deal 10% bonus Pure damage over 3 seconds.",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "Allegiance",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Empower",
								"IsConsumable": false,
								"DurationMs": -1,
								"ActivatedBy": "Attack",
								"AttachedEffects": [
									{
										"Type": "DOT",
										"DamageType": "Pure",
										"OverlapProcessType": "Sum",
										"DurationMs": 3000,
										"FrequencyMs": 1000,
										"Expression": {
											"Percentage": 16,
											"Stat": "AttackDamage",
											"StatSource": "Sender"
										}
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Smoldering Strike II",
	"DisplayDescription": "Your units attacks deal 16% bonus Pure damage over 3 seconds.",
	"Description": {
		"Format": "Your units attacks deal {DamageValue}% bonus Pure damage over {Duration} seconds.",
		"Parameters": {
			"DamageValue": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].Expression.Percentage"
			},
			"Duration": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].DurationMs",
				"ValueMultiplier": 0.001
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Granite_Stage2.json
{
	"Name": "Granite",
	"Stage": 2,
	"Type": "Game",
	"DisplayName": "Granite Module",
	"DisplayDescription": "Gain a Granite Imprint.",
	"Description": {
		"Format": "Gain a Granite Imprint.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Granite",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/ThreefoldPower_Stage3.json
{
	"Name": "ThreefoldPower",
	"Stage": 3,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "ThreefoldPower 3 - Ability",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "ThreefoldPower 3 - Skill",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "Tier",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally",
						"Tier": 3,
						"Num": 3
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"DurationMs": -1,
								"Expression": 500000
							},
							{
								"Type": "Buff",
								"Stat": "AttackSpeed",
								"DurationMs": -1,
								"FrequencyMs": 1000,
								"Expression": {
									"Percentage": 50,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "ThreefoldPower III",
	"DisplayDescription": "3 random Tier 3 Units gain 500 Health and 50% Attack Speed.",
	"Description": {
		"Format": "{UnitNum} random Tier 3 Units gain {HPVal} Health and {ASVal}% Attack Speed.",
		"Parameters": {
			"UnitNum": {
				"ParameterPath": "Abilities[0].Skills[0].Targeting.Num"
			},
			"HPVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			},
			"ASVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression.Percentage"
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Fire_Stage1.json
{
	"Name": "Fire",
	"Stage": 1,
	"Type": "Game",
	"DisplayName": "Fire Module",
	"DisplayDescription": "Gain a Fire Imprint.",
	"Description": {
		"Format": "Gain a Fire Imprint.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Fire",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/ChampionsFocus_Stage2.json
{
	"Name": "ChampionsFocus",
	"Stage": 2,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "Champion's Focus 2 - Ability",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Champion's Focus 2 - Skill",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "Tier",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally",
						"Tier": 5,
						"Num": 1
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackSpeed",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 50,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 50
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Champion's Focus II",
	"DisplayDescription": "A random Tier 5 Unit gains 50% Attack Speed and 50 Omega Power",
	"Description": {
		"Format": "A random Tier 5 Unit gains {ASVal}% Attack Speed and {OPVal} Omega Power",
		"Parameters": {
			"ASVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			},
			"OPVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression"
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Empath_Stage1.json
{
	"Name": "Empath",
	"Stage": 1,
	"Type": "Game",
	"DisplayName": "Empath Module",
	"DisplayDescription": "Gain a Empath Imprint.",
	"Description": {
		"Format": "Gain a Empath Imprint.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Empath",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/ZeroTierOverdrive_Stage2.json
{
	"Name": "ZeroTierOverdrive",
	"Stage": 2,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "Zero-Tier Overdrive 2 - Ability",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Zero-Tier Overdrive 2 - Skill",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "Tier",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally",
						"Tier": 0
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "VulnerabilityPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 16
							},
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 16,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 16,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 16,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "OmegaDamagePercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 16,
									"Stat": "OmegaDamagePercentage",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Zero-Tier Overdrive II",
	"DisplayDescription": "Your Tier 0 units deal 16% more and receive 16% less damage.",
	"Description": {
		"Format": "Your Tier 0 units deal {DmgAmpVal}% more and receive {DmgRedVal}% less damage.",
		"Parameters": {
			"DmgRedVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression"
			},
			"DmgAmpVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[4].Expression.Percentage"
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}
