=== owng25/arena-gauntlet-personal/json_data_copy/schemas/DroneAugmentData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Drone Augment Data",
	"$ref": "#/$defs/DroneAugmentType",
	"$defs": {
		"DroneAugmentType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Name": {
					"type": "string"
				},
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Stage": {
					"type": "integer"
				},
				"Type": {
					"$ref": "#/$defs/DroneAugmentTypeEnum"
				},
				"RuntimeBonus": {
					"$ref": "#/$defs/RuntimeBonusType"
				}
			},
			"additionalProperties": false
		},
		"DroneAugmentTypeEnum": {
			"type": "string",
			"enum": [ "Simulation", "Game", "ServerAndGame"]
		},
		"RuntimeBonusType": {
			"type": "object",
			"properties": {
				"GrantedAugments": {
					"type": "array",
					"items": {
						"$ref": "AugmentData.schema.json#/$defs/AugmentTypeID"
					}
				},
				"GrantedCredits": {
					"type": "integer"
				}

			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Dust_Stage2.json
{
	"Name": "Dust",
	"Stage": 2,
	"Type": "Game",
	"DisplayName": "Dust Module",
	"DisplayDescription": "Gain a Dust Imprint.",
	"Description": {
		"Format": "Gain a Dust Imprint.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Dust",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Utility/WindborneWard_Stage2.json
{
	"Name": "WindborneWard",
	"Stage": 2,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "WindborneWard2_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "WindborneWard2 - Targeting",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Airborne",
							"Underground"
						]
					},
					"Targeting": {
						"Type": "Allegiance",
						"Group": "Ally",
						"Guidance": [
							"Ground",
							"Airborne",
							"Underground"
						]
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "SpawnMark",
								"MarkType": "Beneficial",
								"DurationMs": -1,
								"AttachedAbilities": [
									{
										"Name": "WindborneWard2 - Sub Ability",
										"ActivationTrigger": {
											"TriggerType": "OnActivateXAbilities",
											"AbilityTypes": [
												"Omega"
											],
											"EveryX": true,
											"NumberOfAbilitiesActivated": 1
										},
										"TotalDurationMs": 0,
										"Skills": [
											{
												"Name": "WindborneWard2 - Burn Energy",
												"Targeting": {
													"Type": "DistanceCheck",
													"Guidance": [
														"Ground",
														"Underground",
														"Airborne"
													],
													"Group": "Enemy",
													"Lowest": true,
													"Num": 1
												},
												"Deployment": {
													"Type": "Direct",
													"Guidance": [
														"Ground",
														"Underground",
														"Airborne"
													]
												},
												"EffectPackage": {
													"Effects": [
														{
															"Type": "InstantEnergyBurn",
															"Expression": 24000
														}
													]
												}
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Windborne Ward II",
	"DisplayDescription": "When your units use the Omega, they burn 24 energy from their closest enemy.",
	"Description": {
		"Format": "When your units use the Omega, they burn {EnergyVal} energy from their closest enemy.",
		"Parameters": {
			"EnergyVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedAbilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Wildfire_Stage2.json
{
	"Name": "Wildfire",
	"Stage": 2,
	"Type": "Game",
	"DisplayName": "Wildfire Module",
	"DisplayDescription": "Gain a Wildfire Imprint.",
	"Description": {
		"Format": "Gain a Wildfire Imprint.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Wildfire",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Earth_Stage1.json
{
	"Name": "Earth",
	"Stage": 1,
	"Type": "Game",
	"DisplayName": "Earth Module",
	"DisplayDescription": "Gain a Earth Imprint.",
	"Description": {
		"Format": "Gain a Earth Imprint.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Earth",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Spore_Stage3.json
{
	"Name": "Spore",
	"Stage": 3,
	"Type": "Game",
	"DisplayName": "Spore Matrix",
	"DisplayDescription": "Gain a Spore Imprint and a Vanquisher's Barrier.",
	"Description": {
		"Format": "Gain a Spore Imprint and a Vanquisher's Barrier.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Spore",
				"Stage": 0,
				"Variation": "Original"
			},
			{
				"Name": "VanquishersBarrier",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/VeteransMight_Stage3.json
{
	"Name": "VeteransMight",
	"Stage": 3,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "Veteran's Might 2 - Ability",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Veteran's Might 2 - Skill",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "Tier",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally",
						"Tier": 4,
						"Num": 2
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 50,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 50,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 50,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalVampPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 12
							},
							{
								"Type": "Buff",
								"Stat": "EnergyVampPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 12
							},
							{
								"Type": "Buff",
								"Stat": "PureVampPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 12
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Veteran's Might III",
	"DisplayDescription": "2 random Tier 4 Units gain 50% Attack Damage and 12% Omnivamp.",
	"Description": {
		"Format": "{UnitNum} random Tier 4 Units gain {ADVal}% Attack Damage and {VampVal}% Omnivamp.",
		"Parameters": {
			"UnitNum": {
				"ParameterPath": "Abilities[0].Skills[0].Targeting.Num"
			},
			"ADVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			},
			"VampVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[3].Expression"
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Predator_Stage3.json
{
	"Name": "Predator",
	"Stage": 3,
	"Type": "Game",
	"DisplayName": "Predator Matrix",
	"DisplayDescription": "Gain a Predator Imprint and an Overguard.",
	"Description": {
		"Format": "Gain a Predator Imprint and an Overguard.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Predator",
				"Stage": 0,
				"Variation": "Original"
			},
			{
				"Name": "UmbralStride",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Utility/Energizer_Stage2.json
{
	"Name": "Energizer",
	"Stage": 2,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "All allied units gain 8 Energy Regen.",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "All allied units gain 8 Energy Regen.",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Allegiance",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "EnergyRegeneration",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 400
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Energizer II",
	"DisplayDescription": "All allied units gain 4 Energy Regen.",
	"Description": {
		"Format": "All allied units gain {EnergyVal} Energy Regen.",
		"Parameters": {
			"EnergyVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.01
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}
