=== owng25/arena-gauntlet-personal/json_data_copy/schemas/DroneAugmentData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Drone Augment Data",
	"$ref": "#/$defs/DroneAugmentType",
	"$defs": {
		"DroneAugmentType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Name": {
					"type": "string"
				},
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Stage": {
					"type": "integer"
				},
				"Type": {
					"$ref": "#/$defs/DroneAugmentTypeEnum"
				},
				"RuntimeBonus": {
					"$ref": "#/$defs/RuntimeBonusType"
				}
			},
			"additionalProperties": false
		},
		"DroneAugmentTypeEnum": {
			"type": "string",
			"enum": [ "Simulation", "Game", "ServerAndGame"]
		},
		"RuntimeBonusType": {
			"type": "object",
			"properties": {
				"GrantedAugments": {
					"type": "array",
					"items": {
						"$ref": "AugmentData.schema.json#/$defs/AugmentTypeID"
					}
				},
				"GrantedCredits": {
					"type": "integer"
				}

			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/LightningSpeed_Stage3.json
{
	"Name": "LightningSpeed",
	"Stage": 3,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "All allied units Move and Attack 50% Faster",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "All allied units Move and Attack 50% Faster",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Allegiance",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackSpeed",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 25,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "MoveSpeedSubUnits",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 25,
									"Stat": "MoveSpeedSubUnits",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Lightning Speed III",
	"DisplayDescription": "All allied units Move and Attack 25% Faster",
	"Description": {
		"Format": "All allied units Move and Attack {ASMSVal}% Faster",
		"Parameters": {
			"ASMSVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Combat/CombatRhythm_Stage2.json
{
	"Name": "CombatRhythm",
	"Stage": 2,
	"Type": "Simulation",
	"Abilities": [
		{
			"Name": "CombatRhythm2_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "CombatRhythm2 - Targeting",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Airborne",
							"Underground"
						]
					},
					"Targeting": {
						"Type": "Allegiance",
						"Group": "Ally",
						"Guidance": [
							"Ground",
							"Airborne",
							"Underground"
						]
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "SpawnMark",
								"MarkType": "Beneficial",
								"DurationMs": -1,
								"AttachedAbilities": [
									{
										"Name": "Combat Rhythm 2 - Ability",
										"ActivationTrigger": {
											"TriggerType": "OnVanquish",
											"Allegiance": "Self"
										},
										"TotalDurationMs": 0,
										"Skills": [
											{
												"Name": "Combat Rhythm 2 - Buffs",
												"Deployment": {
													"Type": "Direct"
												},
												"Targeting": {
													"Type": "Self"
												},
												"EffectPackage": {
													"Effects": [
														{
															"Type": "Buff",
															"Stat": "AttackPhysicalDamage",
															"OverlapProcessType": "Stacking",
															"DurationMs": -1,
															"Expression": {
																"Percentage": 16,
																"Stat": "AttackPhysicalDamage",
																"StatSource": "Receiver",
																"StatEvaluationType": "Base"
															}
														},
														{
															"Type": "Buff",
															"Stat": "AttackEnergyDamage",
															"OverlapProcessType": "Stacking",
															"DurationMs": -1,
															"Expression": {
																"Percentage": 16,
																"Stat": "AttackEnergyDamage",
																"StatSource": "Receiver",
																"StatEvaluationType": "Base"
															}
														},
														{
															"Type": "Buff",
															"Stat": "AttackPureDamage",
															"OverlapProcessType": "Stacking",
															"DurationMs": -1,
															"Expression": {
																"Percentage": 16,
																"Stat": "AttackPureDamage",
																"StatSource": "Receiver",
																"StatEvaluationType": "Base"
															}
														},
														{
															"Type": "Buff",
															"Stat": "PhysicalVampPercentage",
															"OverlapProcessType": "Stacking",
															"DurationMs": -1,
															"Expression": 16
														},
														{
															"Type": "Buff",
															"Stat": "EnergyVampPercentage",
															"OverlapProcessType": "Stacking",
															"DurationMs": -1,
															"Expression": 16
														},
														{
															"Type": "Buff",
															"Stat": "PureVampPercentage",
															"OverlapProcessType": "Stacking",
															"DurationMs": -1,
															"Expression": 16
														}
													]
												}
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Combat Rhythm II",
	"DisplayDescription": "Your units gain 16% Omnivamp and Attack Damage when they eliminate an enemy.",
	"Description": {
		"Format": "Your units gain {Omnivamp}% Omnivamp and Attack Damage when they eliminate an enemy.",
		"Parameters": {
			"Omnivamp": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedAbilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			}
		}
	},
	"RuntimeBonus": {
		"GrantedAugments": [],
		"GrantedCredits": 0
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/DroneAugmentData/Synergy/Tsunami_Stage3.json
{
	"Name": "Tsunami",
	"Stage": 3,
	"Type": "Game",
	"DisplayName": "Tsunami Matrix",
	"DisplayDescription": "Gain a Tsunami Imprint and a Mindstorm.",
	"Description": {
		"Format": "Gain a Tsunami Imprint and a Mindstorm.",
		"Parameters": {}
	},
	"RuntimeBonus": {
		"GrantedAugments": [
			{
				"Name": "Tsunami",
				"Stage": 0,
				"Variation": "Original"
			},
			{
				"Name": "Mindstorm",
				"Stage": 0,
				"Variation": "Original"
			}
		],
		"GrantedCredits": 0
	}
}
