=== owng25/arena-gauntlet-personal/json_data_copy/schemas/QuestData.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Quest",
    "$ref": "#/$defs/QuestType",
    "$defs": {
        "QuestType": {
            "type": "object",
            "x-versioned": true,
            "description": "Contains the overall structure of a quest line",
            "additionalProperties": false,
            "properties": {
                "ProductionId": {
                    "type": "string",
                    "description": "The unique id of the quest",
                    "maxLength": 100
                },
                "Name": {
                    "type": "string",
                    "description": "A friendly name for the quest",
                    "maxLength": 500
                },
                "Description": {
                    "type": "string",
                    "description": "A friendly description that will be displayed to the player. This could be a basic description, or a more advanced narrative piece.",
                    "maxLength": 500
                },
                "Game": {
                    "type": "string",
                    "description": "The game that the quest is for",
                    "enum": [ "Arena", "Overworld", "Zero", "Beyond" ]
                },
                "Conditions": {
                    "type": "array",
                    "description": "The conditions that must be met before the quest can be started",
                    "maxItems": 5,
                    "items": {
                        "$ref": "MissionTemplateData.schema.json#/$defs/ConditionTemplate",
                        "oneOf": [
                            {
                                "$ref": "MissionTemplateData.schema.json#/$defs/QuestConditionTemplate"
                            },
                            {
                                "$ref": "MissionTemplateData.schema.json#/$defs/FactionConditionTemplate"
                            },
                            {
                                "$ref": "MissionTemplateData.schema.json#/$defs/RangerLevelConditionTemplate"
                            },
                            {
                                "$ref": "MissionTemplateData.schema.json#/$defs/TimeConditionTemplate"
                            }
                        ]
                    }
                },
                "States": {
                    "type": "array",
                    "description": "The set of states defining the quest progression. Organized as a tree to support branching quests",
                    "minItems": 1,
                    "items": { "$ref": "#/$defs/QuestState" }
                },
                "Rewards": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                        "$ref": "MissionTemplateData.schema.json#/$defs/RewardTemplate",
                        "oneOf": [
                            {
                                "$ref": "MissionTemplateData.schema.json#/$defs/FactionRewardTemplate"
                            },
                            {
                                "$ref": "MissionTemplateData.schema.json#/$defs/ItemRewardTemplate"
                            },
                            {
                                "$ref": "#/$defs/QuestRewardTemplate"
                            }
                        ]
                    }
                }
            },
            "required": [ "ProductionId", "Name", "Game", "States" ]
        },
        "QuestState": {
            "type": "object",
            "description": "Defines a node in the quest progression",
            "additionalProperties": false,
			"properties": {
				"StateId": {
					"type": "string",
					"description": "The unique id of the quest state",
					"maxLength": 100
				},
				"Name": {
					"type": "string",
					"description": "A friendly name for the quest state",
					"maxLength": 500
				},
				"Description": {
					"type": "string",
					"description": "A friendly description that will be displayed to the player. This could be a basic description, or a more advanced narrative piece.",
					"maxLength": 500
				},
				"Optional": {
					"type": "boolean",
					"description": "Reserved for future use"
				},
				"Parents": {
					"type": "array",
					"description": "The ProductionId of the previous state(s) in the quest tree, which must be completed before this one may be started. If more than one, only one is required (indicates branch paths coming back together)",
					"items": { "type": "string" }
				},
				"Children": {
					"type": "array",
					"description": "ProductionIds of the state(s) following this one in the quest tree. If more than one, branch selection is determined by the CompletionTag.",
					"items": { "type": "string" }
				},
				"Conditions": {
					"type": "array",
					"description": "Conditions for beginning this State. Used for branching.",
					"items": {
						"$ref": "MissionTemplateData.schema.json#/$defs/ConditionTemplate",
						"oneOf": [
							{
								"$ref": "#/$defs/QuestStateConditionTemplate"
							}

						]
					}
				},
				"Objectives": {
					"type": "array",
					"description": "The objectives that the player must complete for this state",
					"minItems": 1,
					"items": {
						"$ref": "MissionTemplateData.schema.json#/$defs/ObjectiveTemplate",
						"oneOf": [
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/CaptureIlluvialObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/GainIlluvialExperienceObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/ForgeItemObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/FuseIlluvialObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/GatherResourceObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/CatchMorphopodObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/FightEncounterObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/ExtractResourceObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/ScanCountObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/ResearchCountObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/DialogObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/ScanLocationObjectiveTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/TrainerBattleObjectiveTemplate"
							}
						]
					}
				},
				"Rewards": {
					"type": "array",
					"items": {
						"$ref": "MissionTemplateData.schema.json#/$defs/RewardTemplate",
						"oneOf": [
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/FactionRewardTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/AirdropRewardTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/AirdropMultiplierRewardTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/MissionRewardTemplate"
							},
							{
								"$ref": "MissionTemplateData.schema.json#/$defs/ItemRewardTemplate"
							}
						]
					}
				},
				"CompletionTags": {
					"type": "array",
					"description": "Set of allowable tags that can be used for the completion state. Used to control branching.",
					"items": { "type": "string" }
				}
			},
            "required": [
                "StateId",
                "Name",
                "Description",
                "Objectives"
            ]
        },
        "QuestConditionTemplate": {
            "type": "object",
            "$id": "schema:QuestConditionTemplate",
            "$ref": "MissionTemplateData.schema.json#/$defs/ConditionTemplate",
            "description": "Player must complete the specified quest before this quest can be selected",
            "additionalProperties": false,
            "properties": {
                "Type": {
                    "type": "string",
                    "const": "QuestCondition"
                },
                "ProductionId": {
                    "type": "string",
                    "description": "The production id of the quest that must be completed before this quest can be selected"
                }
            },
            "required": [ "Type", "ProductionId" ]
        },
        "QuestStateConditionTemplate": {
            "type": "object",
            "$id": "schema:QuestStateConditionTemplate",
            "$ref": "MissionTemplateData.schema.json#/$defs/ConditionTemplate",
            "description": "Player must complete the specified state with the given CompletionTag before this quest can be selected",
            "additionalProperties": false,
            "properties": {
                "Type": {
                    "type": "string",
                    "const": "QuestStateondition"
                },
                "ProductionId": {
                    "type": "string",
                    "description": "The production id of the state that must be completed prior to this one"
                },
                "CompletionTag": {
                    "type": "string",
                    "description": "The CompletionTag of the prior state to select this one."
                }
            },
            "required": [ "Type", "ProductionId", "CompletionTag" ]
        },
        "QuestRewardTemplate": {
            "type": "object",
            "$ref": "MissionTemplateData.schema.json#/$defs/RewardTemplate",
            "description": "Unlock a new quest",
            "additionalProperties": false,
            "properties": {
                "Type": {
                    "type": "string",
                    "const": "QuestReward"
                },
                "ProductionId": {
                    "type": "string",
                    "description": "The production id of the quest that will be unlocked"
                }
            }
        }
    }
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/QuestData/DA_Quest_Do_Your_Part.json
{
	"ProductionId": "DA_Quest_Do_Your_Part",
	"Name": "Do your part!",
	"Description": "",
	"Game": "Overworld",
	"States": [
		{
			"StateId": "6C5B84054CE48A2CDF34CE90A4F731CB",
			"Name": "Report to Second Officer Mikas",
			"Description": "The new Ranger is sent to the RCT where they will learn how and where they need to help.",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "DialogObjective",
					"Description": "Report to Second Officer Mikas",
					"ObjectiveId": "1F862F5C4BDCDF9CF9688D82043413AC",
					"ProviderTag": "Overworld.NPC.Mikas"
				}
			],
			"Rewards": [],
			"Children": [
				"8E5AD4584CFAC982A861689221581894"
			],
			"Parents": []
		},
		{
			"StateId": "8E5AD4584CFAC982A861689221581894",
			"Name": "The Transducer",
			"Description": "Awesome description",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "GatherResourceObjective",
					"Description": "Gather Selenvium Ore",
					"ObjectiveId": "49B91CB241E9D4AA8DD992AC2B5DF89D",
					"QuantityMinimum": 5,
					"QuantityMaximum": 5,
					"QuantityStep": 5,
					"ItemType": "OverworldOre",
					"Name": "SelenviumOre"
				},
				{
					"Type": "GatherResourceObjective",
					"Description": "Gather Chrovium Ore",
					"ObjectiveId": "9B507F2E47003E147B049EAFB7E9AE5F",
					"QuantityMinimum": 5,
					"QuantityMaximum": 5,
					"QuantityStep": 5,
					"ItemType": "OverworldOre",
					"Name": "ChroviumOre"
				}
			],
			"Rewards": [],
			"Children": [
				"D046281B43CE70F093EFA2A80FA6E1A0"
			],
			"Parents": [
				"6C5B84054CE48A2CDF34CE90A4F731CB"
			]
		},
		{
			"StateId": "D046281B43CE70F093EFA2A80FA6E1A0",
			"Name": "Report to Officer Mikas",
			"Description": "Report to Officer Mikas",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "DialogObjective",
					"Description": "Report to Mikas",
					"ObjectiveId": "32555D9C4F8F65B7CE679698A8044123",
					"ProviderTag": "Overworld.NPC.Mikas"
				}
			],
			"Rewards": [
				{
					"Type": "ItemReward",
					"ItemType": "CuredShard",
					"ItemName": "CuredShardT0",
					"QuantityMinimum": 1,
					"QuantityMaximum": 1,
					"QuantityStep": 1
				}
			],
			"Children": [
				"B850444C4E98D5A3D6BB02B9C83305B8"
			],
			"Parents": [
				"8E5AD4584CFAC982A861689221581894"
			]
		},
		{
			"StateId": "B850444C4E98D5A3D6BB02B9C83305B8",
			"Name": "Calibration Mesh",
			"Description": "",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "ScanLocationObjective",
					"Description": "Scan Location A",
					"ObjectiveId": "9AE6B7554C22D0F7331B80AFAB258FCA",
					"RegionId": "Region.BrightlandSteppes",
					"Location": "X=-21200.753 Y=10798.188 Z=6322.537"
				},
				{
					"Type": "ScanLocationObjective",
					"Description": "Scan Location B",
					"ObjectiveId": "280F4FB24643760974872B8D481224BE",
					"RegionId": "Region.BrightlandSteppes",
					"Location": "X=-32920.000 Y=9290.000 Z=7280.000"
				},
				{
					"Type": "ScanLocationObjective",
					"Description": "Scan Location C",
					"ObjectiveId": "AD48C1C9474A7242C39FA480CF99445E",
					"RegionId": "Region.BrightlandSteppes",
					"Location": "X=-26988.991 Y=-7664.212 Z=4441.576"
				}
			],
			"Rewards": [],
			"Children": [
				"330FC6A440D9FC7B1FAB72845B6CAC9C"
			],
			"Parents": [
				"D046281B43CE70F093EFA2A80FA6E1A0"
			]
		},
		{
			"StateId": "330FC6A440D9FC7B1FAB72845B6CAC9C",
			"Name": "Capture Illuvial",
			"Description": "",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "CaptureIlluvialObjective",
					"Description": "Capture Illuvial",
					"ObjectiveId": "84B42DEC43EE57E52E506BB29783EEF4",
					"QuantityMinimum": 1,
					"QuantityMaximum": 1,
					"QuantityStep": 1,
					"Line": "Axolotl",
					"Stage": 1
				}
			],
			"Rewards": [],
			"Children": [
				"605DC0A741FDADFE57E688AD74227984"
			],
			"Parents": [
				"B850444C4E98D5A3D6BB02B9C83305B8"
			]
		},
		{
			"StateId": "605DC0A741FDADFE57E688AD74227984",
			"Name": "Report To Officer Mikas",
			"Description": "Report To Officer Mikas",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "DialogObjective",
					"Description": "Speak to Officer Mikas",
					"ObjectiveId": "83D522904754405729C0C295BF8DE6BF",
					"ProviderTag": "Overworld.NPC.Mikas"
				}
			],
			"Rewards": [],
			"Children": [
				"F9CD52344DCEE14AFB8C4CAC9499D5D5"
			],
			"Parents": [
				"330FC6A440D9FC7B1FAB72845B6CAC9C"
			]
		},
		{
			"StateId": "F9CD52344DCEE14AFB8C4CAC9499D5D5",
			"Name": "Fight Officer Mikas",
			"Description": "Fight Officer Mikas",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "TrainerBattleObjective",
					"Description": "",
					"ObjectiveId": "C6EBF1AE416420DB2C88C08BFE055492",
					"ProviderTag": "Overworld.NPC.Mikas",
					"EnemyUnits": [
						{
							"TypeId":
							{
								"UnitType": "Illuvial",
								"Line": "PistolShrimp",
								"Stage": 1,
								"Path": "Default",
								"Variation": "Original"
							},
							"Position":
							{
								"Q": -22,
								"R": -10
							},
							"Level": 1,
							"Finish": "Colour"
						},
						{
							"TypeId":
							{
								"UnitType": "Illuvial",
								"Line": "Axolotl",
								"Stage": 1,
								"Path": "Default",
								"Variation": "Original"
							},
							"Position":
							{
								"Q": -2,
								"R": -22
							},
							"Level": 1,
							"Finish": "Colour"
						}
					],
					"Mods": []
				}
			],
			"Rewards": [],
			"Children": [
				"DF1A0F5048D7024EB0835A890D757E04"
			],
			"Parents": [
				"605DC0A741FDADFE57E688AD74227984"
			]
		},
		{
			"StateId": "DF1A0F5048D7024EB0835A890D757E04",
			"Name": "",
			"Description": "",
			"Optional": false,
			"CompletionTags": [],
			"Conditions": [],
			"Objectives": [
				{
					"Type": "DialogObjective",
					"Description": "Speak to Officer Mikas",
					"ObjectiveId": "A65E7CDA49E90A64C3572AA41A9B6B7F",
					"ProviderTag": "Overworld.NPC.Mikas"
				}
			],
			"Rewards": [
				{
					"Type": "ItemReward",
					"ItemType": "OverworldDroneEquipment",
					"ItemName": "AtomicConjurant_Stage1",
					"QuantityMinimum": 1,
					"QuantityMaximum": 1,
					"QuantityStep": 1
				}
			],
			"Children": [],
			"Parents": [
				"F9CD52344DCEE14AFB8C4CAC9499D5D5"
			]
		}
	]
}
