=== owng25/arena-gauntlet-personal/json_data_copy/schemas/SuitData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Combat Suit Data",
	"$ref": "#/$defs/CombatSuitType",
	"$defs": {
		"CombatSuitType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"Stats": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatStatsType"
				},

				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Type": {
					"$ref": "#/$defs/SuitTypeEnum"
				}
			},
			"additionalProperties": false
		},
		"SuitTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Amplifier"]
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Impervium_Stage3_Default_Original.json
{
	"Name": "Impervium",
	"Stage": 3,
	"Tier": 3,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 90,
		"EnergyResist": 90,
		"MaxHealth": 2000000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 1500,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "Buff Dodge Chance",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Buff All Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "VulnerabilityPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 20
							}
						]
					}
				}
			]
		},
		{
			"Name": "Every 5 seconds Heal for 5% of Max Health and Burn the nearest Enemy.",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 5000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Every 5 seconds Heal for 5% of Max Health",
					"Targeting": {
						"Type": "Self"
					},
					"Deployment": {
						"Type": "Direct"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantHeal",
								"HealType": "Normal",
								"Expression": 100000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Forged Impervium",
	"DisplayDescription": "Health: 2,000\r\nPhysical Resist: 90\r\nEnergy Resist: 90\r\nMovement Speed: 15\r\n\r\nPassive: Reduce all incoming damage by 20%. Heal 100 every 5 seconds.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Reduce all incoming damage by {d}%. Heal {e} every {f} seconds.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression"
			},
			"e": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			},
			"f": {
				"ParameterPath": "Abilities[1].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 2,000\r\nPhysical Resist: 90\r\nEnergy Resist: 90\r\nMovement Speed: 15\r\n\r\nPassive: Reduce all incoming damage by 20%. Heal 100 every 5 seconds."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Fusion/CriticalSurge_Original.json
{
	"Name": "CriticalSurge",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "CriticalSurge_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "CriticalSurge - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							},
							{
								"Type": "Buff",
								"Stat": "CritChancePercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		},
		{
			"Name": "CriticalSurge_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnDealCrit"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "CriticalSurge - Gain Omega Power on Crit",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 3
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Critical Surge",
	"DisplayDescription": "Critical attacks grant <OmegaPowerPercentage>3</> <OmegaPowerPercentage>Omega Power</>.\r\n\r\nStats:\r\n+10% <AttackDamage>Attack Damage</>\r\n+10 <OmegaPowerPercentage>Omega Power</>\r\n+10% <CritChancePercentage>Crit Chance</>",
	"Description": {
		"Format": "Critical attacks grant <OmegaPowerPercentage>{OPValue}</> <OmegaPowerPercentage>Omega Power</>.\r\n\r\nStats:\r\n+{Stat_AD}% <AttackDamage>Attack Damage</>\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>\r\n+{Stat_CC}% <CritChancePercentage>Crit Chance</>",
		"Parameters": {
			"OPValue": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_AD": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[3].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_CC": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[4].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Critical attacks grant 3 Omega Power.\r\n\r\nStats:\r\n+10% Attack Damage\r\n+10 Omega Power\r\n+10% Crit Chance"
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Support/Eldersurge_Original.json
{
	"Name": "Eldersurge",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "Eldersurge_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Eldersurge - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 100000
							},
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		},
		{
			"Name": "Eldersurge_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Eldersurge - Ally Heal Efficiency",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "Allegiance",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Ally",
						"Self": false
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "HealthGainEfficiencyPercentage",
								"OverlapProcessType": "Sum",
								"DurationMs": -1,
								"Expression": 25
							}
						]
					}
				}
			]
		},
		{
			"Name": "Eldersurge_Ability2",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 10000,
				"MaxActivations": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Eldersurge - Self Heal Efficiency",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "HealthGainEfficiencyPercentage",
								"OverlapProcessType": "Sum",
								"DurationMs": -1,
								"Expression": 50
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Eldersurge",
	"DisplayDescription": "Combat Start: Holder's allies receive <HealthGainEfficiencyPercentage>25%</> more <HealthGainEfficiencyPercentage>Healing</>.\r\n\r\nAfter 10 seconds, the holder gains double the amount.\r\n\r\nStats:\r\n+100 <MaxHealth>Health</>\r\n+10 <OmegaPowerPercentage>Omega Power</>",
	"Description": {
		"Format": "Combat Start: Holder's allies receive <HealthGainEfficiencyPercentage>{HealEffAlly}%</> more <HealthGainEfficiencyPercentage>Healing</>.\r\n\r\nAfter {TriggerTime} seconds, the holder gains double the amount.\r\n\r\nStats:\r\n+{Stat_Health} <MaxHealth>Health</>\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>",
		"Parameters": {
			"HealEffAlly": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"TriggerTime": {
				"ParameterPath": "Abilities[2].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			},
			"Stat_Health": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Combat Start: Holder's allies receive 25% more Healing.\r\n\r\nAfter 10 seconds, the holder gains double the amount.\r\n\r\nStats:\r\n+100 Health\r\n+10 Omega Power"
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Amplifier/CrashingBastion_Default_Original.json
{
	"Name": "CrashingBastion",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"Stats": {
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"MaxHealth": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 0,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "Crashing Bastion",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Aerocloak - Shield With Explosion",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "DistanceCheck",
						"Group": "Ally",
						"Self": true,
						"Lowest": false,
						"Num": 3,
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "SpawnShield",
								"DurationMs": 5000,
								"Expression": {
									"Percentage": 10,
									"Stat": "MaxHealth",
									"StatSource": "Receiver"
								},
								"OnDestroy": {
									"Name": "Shield Explosion",
									"Targeting": {
										"Type": "Self"
									},
									"Deployment": {
										"Type": "Zone"
									},
									"Zone": {
										"Shape": "Hexagon",
										"RadiusUnits": 20,
										"DurationMs": 100,
										"FrequencyMs": 100,
										"ApplyOnce": true
									},
									"EffectPackage": {
										"Effects": [
											{
												"Type": "InstantDamage",
												"DamageType": "Energy",
												"Expression": {
													"Percentage": 10,
													"Stat": "MaxHealth",
													"StatSource": "Sender"
												}
											}
										]
									}
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Crashing Bastion",
	"DisplayDescription": "On Combat Start, the Ranger and the 3 closest allies gain a Shield equal to <MaxHealth>10%</><MaxHealth></> of their <MaxHealth>Max Health</> for 5 seconds. When the Shields expire, they explode, dealing damage equal to the initial Shield amount.",
	"Description": {
		"Format": "On Combat Start, the Ranger and the {AllyNum} closest allies gain a Shield equal to <MaxHealth>{ShieldVal}%</><MaxHealth></> of their <MaxHealth>Max Health</> for {ShieldDuration} seconds. When the Shields expire, they explode, dealing damage equal to the initial Shield amount.",
		"Parameters": {
			"AllyNum": {
				"ParameterPath": "Abilities[0].Skills[0].Targeting.Num"
			},
			"ShieldVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			},
			"ShieldDuration": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "On Combat Start, the Ranger and the 3 closest allies gain a Shield equal to 10% of their Max Health for 5 seconds. When the Shields expire, they explode, dealing damage equal to the initial Shield amount."
}
