=== owng25/arena-gauntlet-personal/json_data_copy/schemas/SuitData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Combat Suit Data",
	"$ref": "#/$defs/CombatSuitType",
	"$defs": {
		"CombatSuitType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"Stats": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatStatsType"
				},

				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Type": {
					"$ref": "#/$defs/SuitTypeEnum"
				}
			},
			"additionalProperties": false
		},
		"SuitTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Amplifier"]
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Starmail_Stage3_Default_Original.json
{
	"Name": "Starmail",
	"Stage": 3,
	"Tier": 2,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 95,
		"EnergyResist": 95,
		"MaxHealth": 1900000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 2200,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "Holder has True Sight, 30% increased Attack Damage, and 30% increased Attack Speed.",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "True Sight and Attack Damage",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 40,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 40,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 40,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		},
		{
			"Name": "On Critical, Holder and its two Nearest Allies gain 6% Crit Amp. (Max 30 Stacks)",
			"ActivationTrigger": {
				"TriggerType": "OnDealCrit"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Savagery Buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"MaxStacks": 10,
								"Expression": {
									"Percentage": 2,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"MaxStacks": 10,
								"Expression": {
									"Percentage": 2,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"MaxStacks": 10,
								"Expression": {
									"Percentage": 2,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Nova Starmail",
	"DisplayDescription": "Health: 1,900\r\nPhysical Resist: 95\r\nEnergy Resist: 95\r\nMovement Speed: 22\r\n\r\nPassive: Gain 40% Attack Damage. Critical Attacks give a stack of 2% Attack Damage, up to 10 stacks.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Gain {d}% Attack Damage. Critical Attacks give a stack of {e}% Attack Damage, up to {f} stacks.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression.Percentage"
			},
			"e": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[1].Expression.Percentage"
			},
			"f": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[2].MaxStacks"
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 1,900\r\nPhysical Resist: 95\r\nEnergy Resist: 95\r\nMovement Speed: 22\r\n\r\nPassive: Gain 40% Attack Damage. Critical Attacks give a stack of 2% Attack Damage, up to 10 stacks."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Amplifier/Jumpsuit_For_Amplifier_Default_Original.json
{
	"Name": "Jumpsuit",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"MaxHealth": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 0,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [],
	"DisplayName": "Jumpsuit",
	"DisplayDescription": "<Italic>The Jumpsuit can be enhanced during the Suit Amplifier Round.</>",
	"Description": {
		"Format": "<Italic>The Jumpsuit can be enhanced during the Suit Amplifier Round.</>",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The Jumpsuit can be enhanced during the Suit Amplifier Round."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Neuroplate_Stage2_Default_Original.json
{
	"Name": "Neuroplate",
	"Stage": 2,
	"Tier": 2,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 55,
		"EnergyResist": 65,
		"MaxHealth": 1000000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 1500,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "OP dmg increase",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Increase OP Damage",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaDamagePercentage",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 30,
									"Stat": "OmegaDamagePercentage",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Cortex Neuroplate",
	"DisplayDescription": "Health: 1,000\r\nPhysical Resist: 55\r\nEnergy Resist: 65\r\nMovement Speed: 15\r\n\r\nPassive: Omega Ability damage is increased by 30%.\r\n\r\nMindflare Neuroplate: Omega Ability damage is increased by 40%. The Omega Ability refunds 20% of your Energy.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Omega Ability damage is increased by {d}%.\r\n\r\nMindflare Neuroplate: Omega Ability damage is increased by 40%. The Omega Ability refunds 20% of your Energy.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 1,000\r\nPhysical Resist: 55\r\nEnergy Resist: 65\r\nMovement Speed: 15\r\n\r\nPassive: Omega Ability damage is increased by 30%.\r\n\r\nMindflare Neuroplate: Omega Ability damage is increased by 40%. The Omega Ability refunds 20% of your Energy."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Energy/Mindstorm_Original.json
{
	"Name": "Mindstorm",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "Mindstorm_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Mindstorm - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 20
							},
							{
								"Type": "Buff",
								"Stat": "AttackSpeed",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		},
		{
			"Name": "Mindstorm_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Mindstorm - Gain Energy",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "EnergyRegeneration",
								"OverlapProcessType": "Sum",
								"DurationMs": 5000,
								"Expression": 500
							}
						]
					}
				}
			]
		},
		{
			"Name": "Mindstorm_Ability2",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 5000,
				"MaxActivations": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Mindstorm - Gain Omega Power",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 15
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Mindstorm",
	"DisplayDescription": "Combat Start: Gain <EnergyRegeneration>5</> <EnergyRegeneration>Energy Regen</> for 5 seconds. Afterwards, gain <OmegaPowerPercentage>15</> <OmegaPowerPercentage>Omega Power</>.\r\n\r\nStats:\r\n+20 <OmegaPowerPercentage>Omega Power</>\r\n+10% <AttackSpeed>Attack Speed</>",
	"Description": {
		"Format": "Combat Start: Gain <EnergyRegeneration>{EnergyVal}</> <EnergyRegeneration>Energy Regen</> for {Duration} seconds. Afterwards, gain <OmegaPowerPercentage>{OPVal}</> <OmegaPowerPercentage>Omega Power</>.\r\n\r\nStats:\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>\r\n+{Stat_AS}% <AttackSpeed>Attack Speed</>",
		"Parameters": {
			"EnergyVal": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			},
			"Duration": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.01
			},
			"OPVal": {
				"ParameterPath": "Abilities[2].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_AS": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression.Percentage",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Combat Start: Gain 5 Energy Regen for 5 seconds. Afterwards, gain 15 Omega Power.\r\n\r\nStats:\r\n+20 Omega Power\r\n+10% Attack Speed"
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Brawler/Phagefire_Original.json
{
	"Name": "Phagefire",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "Phagefire_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Phagefire - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 250000
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		},
		{
			"Name": "Phagefire_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Phagefire_ - Burn",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Aura",
								"AttachedEffects": [
									{
										"Type": "Debuff",
										"Stat": "HealthGainEfficiencyPercentage",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 20,
										"FrequencyMs": 1000,
										"Expression": 25
									}
								]
							}
						]
					}
				}
			]
		},
		{
			"Name": "Phagefire_Ability2",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 1000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Phagefire_ - Poison",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "InZone",
						"Group": "Enemy",
						"RadiusUnits": 20
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Percentage": 1,
									"Stat": "MaxHealth",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Phagefire",
	"DisplayDescription": "Enemies within 20-hexes are Burned and Poisoned.\r\n\r\nStats:\r\n+10% <AttackDamage>Attack Damage</>\r\n+250 <MaxHealth>Health</>\r\n+10 <Resistance>Resistances</>\r\n\r\n<Italic>Burn: Reduces healing received by 25%.</>\r\n\r\n<Italic>Poison: Deals 1% of target's Max Health as Pure Damage per second.</>",
	"Description": {
		"Format": "Enemies within {Radius}-hexes are Burned and Poisoned.\r\n\r\nStats:\r\n+{Stat_AD}% <AttackDamage>Attack Damage</>\r\n+{Stat_Health} <MaxHealth>Health</>\r\n+{Stat_Resist} <Resistance>Resistances</>\r\n\r\n<Italic>Burn: Reduces healing received by 25%.</>\r\n\r\n<Italic>Poison: Deals 1% of target's Max Health as Pure Damage per second.</>",
		"Parameters": {
			"Radius": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].RadiusUnits",
				"ValueMultiplier": 1.0
			},
			"Stat_AD": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"Stat_Health": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[3].Expression",
				"ValueMultiplier": 0.001
			},
			"Stat_Resist": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[4].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Enemies within 20-hexes are Burned and Poisoned.\r\n\r\nStats:\r\n+10% Attack Damage\r\n+250 Health\r\n+10 Resistances\r\n\r\nBurn: Reduces healing received by 25%.\r\n\r\nPoison: Deals 1% of target's Max Health as Pure Damage per second."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Amplifier/CelestialInfusion_Default_Original.json
{
	"Name": "CelestialInfusion",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"Stats": {
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"MaxHealth": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 0,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "Celestial Infusion",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Attack"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 15
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Xenolink - Omega Power",
					"Deployment": {
						"Type": "Direct",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"Targeting": {
						"Type": "InZone",
						"Group": "Ally",
						"Self": true,
						"RadiusUnits": 20,
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						]
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 50
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Celestial Infusion",
	"DisplayDescription": "Every 15th attack, grant <OmegaPowerPercentage>50</><OmegaPowerPercentage></> <OmegaPowerPercentage>Omega Power</> to allies within 20-radius.",
	"Description": {
		"Format": "Every {AttackNum}th attack, grant <OmegaPowerPercentage>{OPVal}</><OmegaPowerPercentage></> <OmegaPowerPercentage>Omega Power</> to allies within {Radius}-radius.",
		"Parameters": {
			"AttackNum": {
				"ParameterPath": "Abilities[0].ActivationTrigger.NumberOfAbilitiesActivated"
			},
			"OPVal": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression"
			},
			"Radius": {
				"ParameterPath": "Abilities[0].Skills[0].Targeting.RadiusUnits"
			}
		}
	},
	"DisplayDescriptionNormalized": "Every 15th attack, grant 50 Omega Power to allies within 20-radius."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Energy/Corroder_Original.json
{
	"Name": "Corroder",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "Corroder_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Corroder - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 25
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		},
		{
			"Name": "Corroder_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Attack"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Corroder - Corrode",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Empower",
								"IsConsumable": true,
								"ActivationsUntilExpiry": 1,
								"ActivatedBy": "Attack",
								"AttachedEffectPackageAttributes": {
									"Propagation": {
										"PropagationType": "Splash",
										"IgnoreFirstPropagationReceiver": false,
										"SplashRadiusUnits": 25,
										"EffectPackage": {
											"Effects": [
												{
													"Type": "Debuff",
													"Stat": "EnergyResist",
													"DurationMs": 5000,
													"Expression": {
														"Percentage": 25,
														"Stat": "EnergyResist",
														"StatSource": "Receiver"
													}
												}
											]
										}
									}
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Corroder",
	"DisplayDescription": "Attacks Corrode the target and all enemies within 25-hexes for 5 seconds.\r\n\r\nStats:\r\n+25 <OmegaPowerPercentage>Omega Power</>\r\n\r\n<Italic>Corrode: Reduces target's Energy Resistances by 25%.</>",
	"Description": {
		"Format": "Attacks Corrode the target and all enemies within {Radius}-hexes for {Duration} seconds.\r\n\r\nStats:\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>\r\n\r\n<Italic>Corrode: Reduces target's Energy Resistances by 25%.</>",
		"Parameters": {
			"Radius": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].AttachedEffectPackageAttributes.Propagation.SplashRadiusUnits",
				"ValueMultiplier": 1.0
			},
			"Duration": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].AttachedEffectPackageAttributes.Propagation.EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Attacks Corrode the target and all enemies within 25-hexes for 5 seconds.\r\n\r\nStats:\r\n+25 Omega Power\r\n\r\nCorrode: Reduces target's Energy Resistances by 25%."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Energy/EssenceSiphon_Original.json
{
	"Name": "EssenceSiphon",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "EssenceSiphon_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "EssenceSiphon - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 20
							},
							{
								"Type": "Buff",
								"Stat": "AttackSpeed",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 5,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							}
						]
					}
				}
			]
		},
		{
			"Name": "EssenceSiphon_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Attack"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "EssenceSiphon - Gain Energy",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantEnergyGain",
								"Expression": 4000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Essence Siphon",
	"DisplayDescription": "Attacks grant <EnergyCost>4</> bonus <EnergyCost>Energy</>.\r\n\r\nStats:\r\n+20 <OmegaPowerPercentage>Omega Power</>\r\n+5% <AttackSpeed>Attack Speed</>",
	"Description": {
		"Format": "Attacks grant <EnergyCost>{EnergyVal}</> bonus <EnergyCost>Energy</>.\r\n\r\nStats:\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>\r\n+{Stat_AS}% <AttackSpeed>Attack Speed</>",
		"Parameters": {
			"EnergyVal": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression"
			},
			"Stat_AS": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression.Percentage"
			}
		}
	},
	"DisplayDescriptionNormalized": "Attacks grant 4 bonus Energy.\r\n\r\nStats:\r\n+20 Omega Power\r\n+5% Attack Speed"
}
