=== owng25/arena-gauntlet-personal/json_data_copy/schemas/SuitData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Combat Suit Data",
	"$ref": "#/$defs/CombatSuitType",
	"$defs": {
		"CombatSuitType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"Stats": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatStatsType"
				},

				"Abilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Type": {
					"$ref": "#/$defs/SuitTypeEnum"
				}
			},
			"additionalProperties": false
		},
		"SuitTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Amplifier"]
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Shield/AbyssRot_Original.json
{
	"Name": "AbyssRot",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "AbyssRot_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "AbyssRot - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 300000
							},
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 15
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 15
							}
						]
					}
				}
			]
		},
		{
			"Name": "AbyssRot_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "AbyssRot - Corrode",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Aura",
								"AttachedEffects": [
									{
										"Type": "Debuff",
										"Stat": "EnergyResist",
										"OverlapProcessType": "Sum",
										"DurationMs": -1,
										"RadiusUnits": 25,
										"FrequencyMs": 1000,
										"Expression": {
											"Percentage": 25,
											"Stat": "EnergyResist",
											"StatSource": "Receiver"
										}
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Abyss Rot",
	"DisplayDescription": "Corrode enemies within 25-hexes.\r\n\r\nStats:\r\n+300 <MaxHealth>Health</>\r\n+10% <AttackDamage>Attack Damage</>\r\n+15 <EnergyResist>Energy Resistance</>\r\n\r\n<Italic>Corrode: Reduces target's Energy Resistances by 25%.</>",
	"Description": {
		"Format": "Corrode enemies within {Radius}-hexes.\r\n\r\nStats:\r\n+{Stat_Health} <MaxHealth>Health</>\r\n+{Stat_AD}% <AttackDamage>Attack Damage</>\r\n+{Stat_EngResist} <EnergyResist>Energy Resistance</>\r\n\r\n<Italic>Corrode: Reduces target's Energy Resistances by 25%.</>",
		"Parameters": {
			"Radius": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"Stat_Health": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			},
			"Stat_AD": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"Stat_EngResist": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[4].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Corrode enemies within 25-hexes.\r\n\r\nStats:\r\n+300 Health\r\n+10% Attack Damage\r\n+15 Energy Resistance\r\n\r\nCorrode: Reduces target's Energy Resistances by 25%."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Energy/ArcaneAccelerator_Original.json
{
	"Name": "ArcaneAccelerator",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "ArcaneAccelerator_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "ArcaneAccelerator - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 20
							},
							{
								"Type": "Buff",
								"Stat": "EnergyVampPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 5
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalVampPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 5
							},
							{
								"Type": "Buff",
								"Stat": "PureVampPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 5
							}
						]
					}
				}
			]
		},
		{
			"Name": "ArcaneAccelerator_Ability1",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 5000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "ArcaneAccelerator - Gain Omega Power",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Arcane Accelerator",
	"DisplayDescription": "Gain <OmegaPowerPercentage>10</> <OmegaPowerPercentage>Omega Power</> every 5 seconds.\r\n\r\nStats:\r\n+20 <OmegaPowerPercentage>Omega Power</>\r\n+5% <Omnivamp>Omnivamp</>",
	"Description": {
		"Format": "Gain <OmegaPowerPercentage>{OPVal}</> <OmegaPowerPercentage>Omega Power</> every {TriggerTime} seconds.\r\n\r\nStats:\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>\r\n+{Stat_Vamp}% <Omnivamp>Omnivamp</>",
		"Parameters": {
			"OPVal": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"TriggerTime": {
				"ParameterPath": "Abilities[1].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_Vamp": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "Gain 10 Omega Power every 5 seconds.\r\n\r\nStats:\r\n+20 Omega Power\r\n+5% Omnivamp"
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Warframe_Stage3_Default_Original.json
{
	"Name": "Warframe",
	"Stage": 3,
	"Tier": 2,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 90,
		"EnergyResist": 70,
		"MaxHealth": 1600000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 2200,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "Pierce 80% of Physical and Energy Resist.",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Piercing buffs",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "PhysicalPiercingPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 40
							},
							{
								"Type": "Buff",
								"Stat": "EnergyPiercingPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 40
							}
						]
					}
				}
			]
		},
		{
			"Name": "Give Frost to enemy on Attack",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Attack"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Tornado knock-up and stun with EnergyDamage",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"PercentageOfAbilityDuration": 0,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Debuff",
								"Stat": "VulnerabilityPercentage",
								"OverlapProcessType": "Merge",
								"DurationMs": 2500,
								"Expression": 5
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Onslaught Warframe",
	"DisplayDescription": "Health: 1,600\r\nPhysical Resist: 90\r\nEnergy Resist: 70\r\nMovement Speed: 22\r\n\r\nPassive: Attacks pierce 40% Resistances. Your target receives 5% increased damage while you attack it.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Attacks pierce {d}% Resistances. Your target receives {e}% increased damage while you attack it.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression"
			},
			"e": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression"
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 1,600\r\nPhysical Resist: 90\r\nEnergy Resist: 70\r\nMovement Speed: 22\r\n\r\nPassive: Attacks pierce 40% Resistances. Your target receives 5% increased damage while you attack it."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Shell_Stage2_Default_Original.json
{
	"Name": "Shell",
	"Stage": 2,
	"Tier": 1,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 70,
		"EnergyResist": 60,
		"MaxHealth": 1100000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 1800,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "Buff Dodge Chance",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart",
				"Allegiance": "Self"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Buff All Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "Grit",
								"OverlapProcessType": "Stacking",
								"Expression": 30000,
								"DurationMs": -1
							},
							{
								"Type": "Buff",
								"Stat": "Resolve",
								"OverlapProcessType": "Stacking",
								"Expression": 30000,
								"DurationMs": -1
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Ionic Shell",
	"DisplayDescription": "Health: 1,100\r\nPhysical Resist: 70\r\nEnergy Resist: 60\r\nMovement Speed: 18\r\n\r\nPassive: Gain 30 Grit and Resolve.\r\n\r\nPlasma Shell: Gain 30 Grit and Resolve, and gain 20% damage reduction.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Gain {d} Grit and Resolve.\r\n\r\nPlasma Shell: Gain 30 Grit and Resolve, and gain 20% damage reduction.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 1,100\r\nPhysical Resist: 70\r\nEnergy Resist: 60\r\nMovement Speed: 18\r\n\r\nPassive: Gain 30 Grit and Resolve.\r\n\r\nPlasma Shell: Gain 30 Grit and Resolve, and gain 20% damage reduction."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Cybercore_Stage2_Default_Original.json
{
	"Name": "Cybercore",
	"Stage": 2,
	"Tier": 4,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 80,
		"EnergyResist": 80,
		"MaxHealth": 1450000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 2500,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "MudSynergy_Empower",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"NumberOfAbilitiesActivated": 1,
				"AbilityTypes": [
					"Attack"
				],
				"EveryX": true
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "AttackSpeed Reduction",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Debuff",
								"Stat": "AttackSpeed",
								"OverlapProcessType": "Merge",
								"DurationMs": 5000,
								"FrequencyMs": 500,
								"MaxStacks": 1,
								"Expression": {
									"Percentage": 30,
									"Stat": "AttackSpeed",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Precision Cybercore",
	"DisplayDescription": "Health: 1,450\r\nPhysical Resist: 80\r\nEnergy Resist: 80\r\nMovement Speed: 25\r\n\r\nPassive: Attacks debuff your target's Attack Speed by 30% for 5 seconds.\r\n\r\nPerfected Cybercore: Attacks steal 30% Attack Speed from your target for 5 seconds.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Attacks debuff your target's Attack Speed by {d}% for {e} seconds.\r\n\r\nPerfected Cybercore: Attacks steal 30% Attack Speed from your target for 5 seconds.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression.Percentage"
			},
			"e": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 1,450\r\nPhysical Resist: 80\r\nEnergy Resist: 80\r\nMovement Speed: 25\r\n\r\nPassive: Attacks debuff your target's Attack Speed by 30% for 5 seconds.\r\n\r\nPerfected Cybercore: Attacks steal 30% Attack Speed from your target for 5 seconds."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/SuitData/Battlesuit_Stage3_Default_Original.json
{
	"Name": "Battlesuit",
	"Stage": 3,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Stats": {
		"PhysicalResist": 110,
		"EnergyResist": 90,
		"MaxHealth": 1100000,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"AttackDodgeChancePercentage": 0,
		"MoveSpeedSubUnits": 1800,
		"OmegaPowerPercentage": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"StartingEnergy": 0,
		"StartingShield": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0
	},
	"Abilities": [
		{
			"Name": "TemplarSynergy_Omega",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Attack"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 3
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Templar Extra Damage",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Empower",
								"IsConsumable": true,
								"ActivationsUntilExpiry": 1,
								"ActivatedBy": "Attack",
								"AttachedEffects": [
									{
										"Type": "InstantDamage",
										"DamageType": "Physical",
										"Expression": {
											"Percentage": 100,
											"Stat": "AttackPhysicalDamage",
											"StatSource": "Sender"
										}
									},
									{
										"Type": "InstantDamage",
										"DamageType": "Energy",
										"Expression": {
											"Percentage": 100,
											"Stat": "AttackEnergyDamage",
											"StatSource": "Sender"
										}
									},
									{
										"Type": "InstantDamage",
										"DamageType": "Pure",
										"Expression": {
											"Percentage": 100,
											"Stat": "AttackPureDamage",
											"StatSource": "Sender"
										}
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Gamma Battlesuit",
	"DisplayDescription": "Health: 1,100\r\nPhysical Resist: 110\r\nEnergy Resist: 90\r\nMovement Speed: 18\r\n\r\nPassive: Deal 100% more damage every third attack.",
	"Description": {
		"Format": "Health: {a}\r\nPhysical Resist: {b}\r\nEnergy Resist: {z}\r\nMovement Speed: {c}\r\n\r\nPassive: Deal {d}% more damage every third attack.",
		"Parameters": {
			"a": {
				"ParameterPath": "Stats.MaxHealth",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "Stats.PhysicalResist"
			},
			"z": {
				"ParameterPath": "Stats.EnergyResist"
			},
			"c": {
				"ParameterPath": "Stats.MoveSpeedSubUnits",
				"ValueMultiplier": 0.01
			},
			"d": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].AttachedEffects[0].Expression.Percentage"
			}
		}
	},
	"DisplayDescriptionNormalized": "Health: 1,100\r\nPhysical Resist: 110\r\nEnergy Resist: 90\r\nMovement Speed: 18\r\n\r\nPassive: Deal 100% more damage every third attack."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Shield/Lifewell_Original.json
{
	"Name": "Lifewell",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "Lifewell_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Lifewell - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "MaxHealth",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 200000
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 15
							},
							{
								"Type": "Buff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 15
							}
						]
					}
				}
			]
		},
		{
			"Name": "Lifewell_Ability1",
			"ActivationTrigger": {
				"TriggerType": "EveryXTime",
				"ActivateEveryTimeMs": 4000
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Lifewell - Heal",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantHeal",
								"HealType": "Normal",
								"Expression": {
									"Percentage": 3,
									"Stat": "MaxHealth",
									"StatSource": "Receiver"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Lifewell",
	"DisplayDescription": "The holder heals <MaxHealth>3%</> of <MaxHealth>Max Health</> every 4 seconds.\r\n\r\nStats:\r\n+200 <MaxHealth>Health</>\r\n+15 <Resistance>Resistances</>",
	"Description": {
		"Format": "The holder heals <MaxHealth>{HealVal}%</> of <MaxHealth>Max Health</> every {TriggerTime} seconds.\r\n\r\nStats:\r\n+{Stat_Health} <MaxHealth>Health</>\r\n+{Stat_Resist} <Resistance>Resistances</>",
		"Parameters": {
			"HealVal": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression.Percentage",
				"ValueMultiplier": 1.0
			},
			"TriggerTime": {
				"ParameterPath": "Abilities[1].ActivationTrigger.ActivateEveryTimeMs",
				"ValueMultiplier": 0.001
			},
			"Stat_Health": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 0.001
			},
			"Stat_Resist": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "The holder heals 3% of Max Health every 4 seconds.\r\n\r\nStats:\r\n+200 Health\r\n+15 Resistances"
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/AugmentData/Forge/Energy/Aethersteal_Original.json
{
	"Name": "Aethersteal",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"Abilities": [
		{
			"Name": "Aethersteal_Stats",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Aethersteal - List of Stats",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 20
							},
							{
								"Type": "Buff",
								"Stat": "CritChancePercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 5
							},
							{
								"Type": "Buff",
								"Stat": "CritAmplificationPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 5
							}
						]
					}
				}
			]
		},
		{
			"Name": "Aethersteal_Ability1",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Omega"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Aethersteal - Steal Omega Power",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "CombatStatCheck",
						"Group": "Enemy",
						"Stat": "OmegaPowerPercentage",
						"Lowest": false,
						"Num": 1
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Debuff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 6
							}
						]
					}
				},
				{
					"Name": "Aethersteal - Self Buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 6
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Aethersteal",
	"DisplayDescription": "On Omega, steal <OmegaPowerPercentage>6</> <OmegaPowerPercentage>Omega Power</> from the highest <OmegaPowerPercentage>Omega Power</> enemy.\r\n\r\nStats:\r\n+20 <OmegaPowerPercentage>Omega Power</>\r\n+5% <CritChancePercentage>Crit Chance</>\r\n+5% <CritAmplificationPercentage>Crit Amp</>",
	"Description": {
		"Format": "On Omega, steal <OmegaPowerPercentage>{StealVal}</> <OmegaPowerPercentage>Omega Power</> from the highest <OmegaPowerPercentage>Omega Power</> enemy.\r\n\r\nStats:\r\n+{Stat_OP} <OmegaPowerPercentage>Omega Power</>\r\n+{Stat_CC}% <CritChancePercentage>Crit Chance</>\r\n+{Stat_CA}% <CritAmplificationPercentage>Crit Amp</>",
		"Parameters": {
			"StealVal": {
				"ParameterPath": "Abilities[1].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_OP": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[0].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_CC": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[1].Expression",
				"ValueMultiplier": 1.0
			},
			"Stat_CA": {
				"ParameterPath": "Abilities[0].Skills[0].EffectPackage.Effects[2].Expression",
				"ValueMultiplier": 1.0
			}
		}
	},
	"DisplayDescriptionNormalized": "On Omega, steal 6 Omega Power from the highest Omega Power enemy.\r\n\r\nStats:\r\n+20 Omega Power\r\n+5% Crit Chance\r\n+5% Crit Amp"
}
