=== owng25/arena-gauntlet-personal/json_data_copy/schemas/WeaponData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Weapon Data",
	"$ref": "#/$defs/CombatWeaponType",
	"$defs": {
		"CombatWeaponType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"DominantCombatAffinity": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatAffinityEnum"
				},
				"DominantCombatClass": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatClassEnum"
				},
				"CombatClass": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatClassEnum"
				},
				"CombatAffinity": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatAffinityEnum"
				},
				"AmplifierForWeapon": {
					"$ref": "#/$defs/WeaponTypeID"
				},
				"Stats": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatStatsType"
				},
				"AttackAbilitiesSelection": {
					"type": "string"
				},
				"AttackAbilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"OmegaAbilitiesSelection": {
					"type": "string"
				},
				"OmegaAbilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"InnateAbilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Type": {
					"$ref": "#/$defs/WeaponTypeEnum"
				},
				"EffectsReplacements": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatEffectType"
					}
				}
			},
			"additionalProperties": false
		},
		"WeaponTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Amplifier"]
		},
		"WeaponTypeID": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"CombatAffinity": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatAffinityEnum"
				}
			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Maul_Stage1_Default_Original.json
{
	"Name": "Maul",
	"Stage": 1,
	"Tier": 5,
	"Variation": "Original",
	"Type": "Normal",
	"CombatAffinity": "Earth",
	"CombatClass": "Empath",
	"DominantCombatAffinity": "Earth",
	"DominantCombatClass": "Empath",
	"Stats": {
		"MaxHealth": 0,
		"StartingEnergy": 60000,
		"EnergyCost": 180000,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 150000,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 60,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 100,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 25,
		"CritAmplificationPercentage": 150,
		"OmegaPowerPercentage": 100,
		"AttackRangeUnits": 3,
		"OmegaRangeUnits": 3,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 100,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 100,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 100,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [
		{
			"Name": "Maul Attack I",
			"Skills": [
				{
					"Name": "Attack",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 50
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Energy",
								"Expression": {
									"Stat": "AttackEnergyDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Stat": "AttackPureDamage",
									"StatSource": "Sender"
								}
							}
						]
					}
				}
			]
		}
	],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [
		{
			"Name": "Willbreaker I",
			"TotalDurationMs": 1500,
			"Skills": [
				{
					"Name": "LIFT THE MAUL",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 75
					},
					"PercentageOfAbilityDuration": 100,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "NegativeState",
								"NegativeState": "Stun",
								"DurationMs": 2000
							}
						]
					}
				},
				{
					"Name": "AOE",
					"Targeting": {
						"Type": "InZone",
						"Group": "Enemy",
						"RadiusUnits": 20
					},
					"Deployment": {
						"Type": "Direct"
					},
					"PercentageOfAbilityDuration": 0,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Operation": "*",
									"Operands": [
										250000,
										{
											"Stat": "OmegaPowerPercentage",
											"StatSource": "Sender"
										}
									]
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Shadow Maul",
	"DisplayDescription": "The Ranger channels dark energy into their maul, delivering a crushing blow that Stuns the target for 2 seconds. The impact creates a shockwave, dealing 250*OP Physical Damage to all enemies within 20 radius.\r\n\r\nAbyssal Maul: Gives Mud.\r\n\r\nDreadmarsh Maul: Gives Mud and Revenant.",
	"Description": {
		"Format": "The Ranger channels dark energy into their maul, delivering a crushing blow that Stuns the target for {a} seconds. The impact creates a shockwave, dealing {b}*OP Physical Damage to all enemies within {c} radius.\r\n\r\nAbyssal Maul: Gives Mud.\r\n\r\nDreadmarsh Maul: Gives Mud and Revenant.",
		"Parameters": {
			"a": {
				"ParameterPath": "OmegaAbilities[0].Skills[0].EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "OmegaAbilities[0].Skills[1].EffectPackage.Effects[0].Expression.Operands[0]",
				"ValueMultiplier": 0.001
			},
			"c": {
				"ParameterPath": "OmegaAbilities[0].Skills[1].Targeting.RadiusUnits"
			}
		}
	},
	"DisplayDescriptionNormalized": "The Ranger channels dark energy into their maul, delivering a crushing blow that Stuns the target for 2 seconds. The impact creates a shockwave, dealing 250*OP Physical Damage to all enemies within 20 radius.\r\n\r\nAbyssal Maul: Gives Mud.\r\n\r\nDreadmarsh Maul: Gives Mud and Revenant."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/EmberlingRod_Amplifier_CauterizingPollination_Default_Original.json
{
	"Name": "EmberlingRodCauterizingPollination",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"AmplifierForWeapon": {
		"Name": "EmberlingRod",
		"Stage": 0,
		"Variation": "Original",
		"CombatAffinity": "Nature"
	},
	"Stats": {
		"MaxHealth": 400000,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 0,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"OmegaPowerPercentage": 0,
		"AttackRangeUnits": 0,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 0,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 0,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"InnateAbilities": [],
	"EffectsReplacements": [
		{
			"ID": "CauterizingPollination",
			"Type": "Debuff",
			"Stat": "HealthGainEfficiencyPercentage",
			"OverlapProcessType": "Merge",
			"DurationMs": 5000,
			"Expression": 25
		},
		{
			"ID": "CauterizingPollination1",
			"Type": "DOT",
			"DamageType": "Energy",
			"DurationMs": 3000,
			"FrequencyMs": 1000,
			"Expression": {
				"Operation": "*",
				"Operands": [
					100000,
					{
						"Stat": "OmegaPowerPercentage",
						"StatSource": "Sender"
					}
				]
			}
		}
	],
	"DisplayName": "Cauterizing Pollination",
	"DisplayDescription": "The initial seed applies Burn for 3 seconds and deals 300 Energy Damage over the duration.",
	"Description": {
		"Format": "The initial seed applies Burn for 3 seconds and deals 300 Energy Damage over the duration.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The initial seed applies Burn for 3 seconds and deals 300 Energy Damage over the duration."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/SproutGuard_Amplifier_ReflectiveBarrier_Default_Original.json
{
	"Name": "SproutGuardReflectiveBarrier",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"AmplifierForWeapon": {
		"Name": "SproutGuard",
		"Stage": 0,
		"Variation": "Original",
		"CombatAffinity": "Earth"
	},
	"Stats": {
		"MaxHealth": 400000,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 0,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"OmegaPowerPercentage": 0,
		"AttackRangeUnits": 0,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 0,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 0,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"InnateAbilities": [
		{
			"Name": "Reflective Barrier",
			"ActivationTrigger": {
				"TriggerType": "OnShieldHit",
				"SenderAllegiance": "Enemy",
				"ReceiverAllegiance": "Self",
				"AbilityTypes": [
					"Attack",
					"Omega"
				]
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "ReflectiveBarrier_Ability1",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Activator"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": 25000
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Reflective Barrier",
	"DisplayDescription": " When any of your Shields are hit, deal 25 Pure damage back to the Attacker.",
	"Description": {
		"Format": " When any of your Shields are hit, deal 25 Pure damage back to the Attacker.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": " When any of your Shields are hit, deal 25 Pure damage back to the Attacker."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/LavaGauntlet_Default_Original.json
{
	"Name": "LavaGauntlet",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"CombatAffinity": "Fire",
	"CombatClass": "Psion",
	"DominantCombatAffinity": "Fire",
	"DominantCombatClass": "Psion",
	"Stats": {
		"MaxHealth": 400000,
		"StartingEnergy": 60000,
		"EnergyCost": 100000,
		"PhysicalResist": 20,
		"EnergyResist": 40,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 60000,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 90,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 100,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 25,
		"CritAmplificationPercentage": 150,
		"OmegaPowerPercentage": 100,
		"AttackRangeUnits": 70,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 100,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 100,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 100,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [
		{
			"Name": "Fire Glove Attack II",
			"Skills": [
				{
					"Name": "Attack",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Projectile",
						"PreDeploymentDelayPercentage": 40
					},
					"Projectile": {
						"SizeUnits": 0,
						"IsHoming": true,
						"SpeedSubUnits": 10000,
						"IsBlockable": false,
						"ApplyToAll": false
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Energy",
								"Expression": {
									"Stat": "AttackEnergyDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Stat": "AttackPureDamage",
									"StatSource": "Sender"
								}
							}
						]
					}
				}
			]
		}
	],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [
		{
			"Name": "Fire Energy Blast",
			"TotalDurationMs": 2000,
			"Skills": [
				{
					"Name": "Damage bomb",
					"Targeting": {
						"Type": "DistanceCheck",
						"Guidance": [
							"Ground",
							"Airborne"
						],
						"Group": "Enemy",
						"Lowest": false,
						"Num": 1
					},
					"Deployment": {
						"Type": "Projectile",
						"Guidance": [
							"Ground",
							"Airborne"
						],
						"PreDeploymentDelayPercentage": 45
					},
					"Projectile": {
						"SizeUnits": 3,
						"IsHoming": true,
						"SpeedSubUnits": 5600,
						"IsBlockable": true,
						"ApplyToAll": false
					},
					"PercentageOfAbilityDuration": 100,
					"EffectPackage": {
						"Attributes": {
							"Propagation": {
								"PropagationType": "Splash",
								"SplashRadiusUnits": 15,
								"DeploymentGuidance": [
									"Ground",
									"Airborne"
								],
								"EffectPackage": {
									"Effects": [
										{
											"ID": "MagmaIntensifier",
											"Type": "InstantDamage",
											"DamageType": "Energy",
											"Expression": {
												"Operation": "*",
												"Operands": [
													300000,
													{
														"Stat": "OmegaPowerPercentage",
														"StatSource": "Sender"
													}
												]
											}
										}
									]
								}
							}
						},
						"Effects": []
					}
				},
				{
					"Name": "Increase omega power",
					"Targeting": {
						"Type": "Self"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 0
					},
					"PercentageOfAbilityDuration": 0,
					"EffectPackage": {
						"Effects": [
							{
								"ID": "EnergyCatalyst",
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 5
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Lava Gauntlet",
	"DisplayDescription": "The Ranger launches an energy bomb at the furthest enemy. When the bomb comes in contact with an enemy it explodes, dealing 300 Energy Damage to all enemies within a 15-radius.\r\n\r\nThe ranger then gains 5 Omega Power for the rest of combat.",
	"Description": {
		"Format": "The Ranger launches an energy bomb at the furthest enemy. When the bomb comes in contact with an enemy it explodes, dealing 300 Energy Damage to all enemies within a 15-radius.\r\n\r\nThe ranger then gains 5 Omega Power for the rest of combat.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The Ranger launches an energy bomb at the furthest enemy. When the bomb comes in contact with an enemy it explodes, dealing 300 Energy Damage to all enemies within a 15-radius.\r\n\r\nThe ranger then gains 5 Omega Power for the rest of combat."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/AquaBlaster_Amplifier_TidalPenetration_Default_Original.json
{
	"Name": "AquaBlasterTidalPenetration",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"AmplifierForWeapon": {
		"Name": "AquaBlaster",
		"Stage": 0,
		"Variation": "Original",
		"CombatAffinity": "Water"
	},
	"Stats": {
		"MaxHealth": 400000,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 0,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"OmegaPowerPercentage": 0,
		"AttackRangeUnits": 0,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 0,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 0,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"InnateAbilities": [
		{
			"Name": "TidalPenetration",
			"ActivationTrigger": {
				"TriggerType": "OnBattleStart"
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "TidalPenetration_Ability",
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 0
					},
					"Targeting": {
						"Type": "Self"
					},
					"PercentageOfAbilityDuration": 0,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "EnergyPiercingPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 70
							},
							{
								"Type": "Buff",
								"Stat": "PhysicalPiercingPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 70
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Tidal Penetration",
	"DisplayDescription": "Gain 70% Resistance Piercing.",
	"Description": {
		"Format": "Gain 70% Resistance Piercing.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "Gain 70% Resistance Piercing."
}
