=== owng25/arena-gauntlet-personal/json_data_copy/schemas/WeaponData.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Weapon Data",
	"$ref": "#/$defs/CombatWeaponType",
	"$defs": {
		"CombatWeaponType": {
			"type": "object",
			"x-versioned": true,
			"properties": {
				"DisplayName": {
					"type": "string"
				},
				"DisplayDescription": {
					"type": "string"
				},
				"DisplayDescriptionNormalized": {
					"type": "string"
				},
				"Description": {
					"$ref": "CombatUnitData.schema.json#/$defs/DescriptionType"
				},
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Tier": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"DominantCombatAffinity": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatAffinityEnum"
				},
				"DominantCombatClass": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatClassEnum"
				},
				"CombatClass": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatClassEnum"
				},
				"CombatAffinity": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatAffinityEnum"
				},
				"AmplifierForWeapon": {
					"$ref": "#/$defs/WeaponTypeID"
				},
				"Stats": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatStatsType"
				},
				"AttackAbilitiesSelection": {
					"type": "string"
				},
				"AttackAbilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"OmegaAbilitiesSelection": {
					"type": "string"
				},
				"OmegaAbilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"InnateAbilities": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatAbilityType"
					}
				},
				"IsDisabled": {
					"type": "boolean"
				},
				"Type": {
					"$ref": "#/$defs/WeaponTypeEnum"
				},
				"EffectsReplacements": {
					"type": "array",
					"items": {
						"$ref": "CombatUnitData.schema.json#/$defs/CombatEffectType"
					}
				}
			},
			"additionalProperties": false
		},
		"WeaponTypeEnum": {
			"type": "string",
			"enum": ["Normal", "Amplifier"]
		},
		"WeaponTypeID": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string"
				},
				"Stage": {
					"type": "integer"
				},
				"Variation": {
					"type": "string"
				},
				"CombatAffinity": {
					"$ref": "CombatUnitData.schema.json#/$defs/CombatAffinityEnum"
				}
			},
			"additionalProperties": false
		}
	}
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/StockGlove_Stage2_Nature_Original.json
{
	"Name": "StockGlove",
	"Stage": 2,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"CombatAffinity": "Nature",
	"CombatClass": "Psion",
	"DominantCombatAffinity": "Nature",
	"DominantCombatClass": "Psion",
	"Stats": {
		"MaxHealth": 0,
		"StartingEnergy": 60000,
		"EnergyCost": 140000,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 67000,
		"AttackPureDamage": 0,
		"AttackSpeed": 80,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 100,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 25,
		"CritAmplificationPercentage": 150,
		"OmegaPowerPercentage": 100,
		"AttackRangeUnits": 70,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 100,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 100,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 100,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [
		{
			"Name": "Nature Glove Attack II",
			"Skills": [
				{
					"Name": "Attack",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Projectile",
						"PreDeploymentDelayPercentage": 40
					},
					"Projectile": {
						"SizeUnits": 0,
						"IsHoming": true,
						"SpeedSubUnits": 10000,
						"IsBlockable": false,
						"ApplyToAll": false
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Energy",
								"Expression": {
									"Stat": "AttackEnergyDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Stat": "AttackPureDamage",
									"StatSource": "Sender"
								}
							}
						]
					}
				}
			]
		}
	],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [
		{
			"Name": "Nature Energy Blast",
			"TotalDurationMs": 2000,
			"Skills": [
				{
					"Name": "Damage bomb",
					"Targeting": {
						"Type": "DistanceCheck",
						"Guidance": [
							"Ground",
							"Airborne"
						],
						"Group": "Enemy",
						"Lowest": false,
						"Num": 1
					},
					"Deployment": {
						"Type": "Projectile",
						"Guidance": [
							"Ground",
							"Airborne"
						],
						"PreDeploymentDelayPercentage": 45
					},
					"Projectile": {
						"SizeUnits": 3,
						"IsHoming": true,
						"SpeedSubUnits": 5600,
						"IsBlockable": true,
						"ApplyToAll": false
					},
					"PercentageOfAbilityDuration": 100,
					"EffectPackage": {
						"Attributes": {
							"Propagation": {
								"PropagationType": "Splash",
								"SplashRadiusUnits": 15,
								"DeploymentGuidance": [
									"Ground",
									"Airborne"
								],
								"EffectPackage": {
									"Effects": [
										{
											"Type": "InstantDamage",
											"DamageType": "Energy",
											"Expression": {
												"Operation": "*",
												"Operands": [
													350000,
													{
														"Stat": "OmegaPowerPercentage",
														"StatSource": "Sender"
													}
												]
											}
										}
									]
								}
							}
						},
						"Effects": []
					}
				},
				{
					"Name": "Increase omega power",
					"Targeting": {
						"Type": "Self"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 0
					},
					"PercentageOfAbilityDuration": 0,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "OmegaPowerPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 7
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Stock Nature Glove II",
	"DisplayDescription": "The Ranger launches an energy bomb at the furthest enemy. When the bomb comes in contact with an enemy it explodes, dealing (350*OP) Energy Damage to all enemies in 15 radius. The ranger then gains 7 Omega Power for the rest of combat.",
	"Description": {
		"Format": "The Ranger launches an energy bomb at the furthest enemy. When the bomb comes in contact with an enemy it explodes, dealing ({a}*OP) Energy Damage to all enemies in {b} radius. The ranger then gains {c} Omega Power for the rest of combat.",
		"Parameters": {
			"a": {
				"ParameterPath": "OmegaAbilities[0].Skills[0].EffectPackage.Attributes.Propagation.EffectPackage.Effects[0].Expression.Operands[0]",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "OmegaAbilities[0].Skills[0].EffectPackage.Attributes.Propagation.SplashRadiusUnits"
			},
			"c": {
				"ParameterPath": "OmegaAbilities[0].Skills[1].EffectPackage.Effects[0].Expression"
			}
		}
	},
	"DisplayDescriptionNormalized": "The Ranger launches an energy bomb at the furthest enemy. When the bomb comes in contact with an enemy it explodes, dealing (350*OP) Energy Damage to all enemies in 15 radius. The ranger then gains 7 Omega Power for the rest of combat."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/StrikeBoomerang_Default_Original.json
{
	"Name": "StrikeBoomerang",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Normal",
	"CombatAffinity": "Fire",
	"CombatClass": "Fighter",
	"DominantCombatAffinity": "Fire",
	"DominantCombatClass": "Fighter",
	"Stats": {
		"MaxHealth": 500000,
		"StartingEnergy": 10000,
		"EnergyCost": 120000,
		"PhysicalResist": 40,
		"EnergyResist": 20,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 70000,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 100,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 100,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 25,
		"CritAmplificationPercentage": 150,
		"OmegaPowerPercentage": 100,
		"AttackRangeUnits": 60,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 100,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 100,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 100,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [
		{
			"Name": "Boomerang Attack I",
			"Skills": [
				{
					"Name": "Attack",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Projectile",
						"PreDeploymentDelayPercentage": 40
					},
					"Projectile": {
						"SizeUnits": 0,
						"IsHoming": true,
						"SpeedSubUnits": 10000,
						"IsBlockable": false,
						"ApplyToAll": false
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Energy",
								"Expression": {
									"Stat": "AttackEnergyDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Stat": "AttackPureDamage",
									"StatSource": "Sender"
								}
							}
						]
					}
				}
			]
		}
	],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [
		{
			"Name": "Ignition Circuit I",
			"TotalDurationMs": 2000,
			"Skills": [
				{
					"Name": "Boomerang",
					"Targeting": {
						"Type": "DistanceCheck",
						"Guidance": [
							"Ground",
							"Underground",
							"Airborne"
						],
						"Group": "Enemy",
						"Lowest": false,
						"Num": 1
					},
					"Deployment": {
						"Type": "Projectile",
						"Guidance": [
							"Ground",
							"Airborne"
						],
						"PreDeploymentDelayPercentage": 50
					},
					"PercentageOfAbilityDuration": 100,
					"Projectile": {
						"SizeUnits": 3,
						"IsHoming": true,
						"SpeedSubUnits": 10000,
						"IsBlockable": false,
						"ApplyToAll": true
					},
					"EffectPackage": {
						"Effects": [
							{
								"ID": "ImpactMagnifier",
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Operation": "*",
									"Operands": [
										300000,
										{
											"Stat": "OmegaPowerPercentage",
											"StatSource": "Sender"
										}
									]
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Strike Boomerang",
	"DisplayDescription": "The Ranger throws the boomerang at the furthest enemy in range, dealing 300 Physical Damage to all enemies hit by it.",
	"Description": {
		"Format": "The Ranger throws the boomerang at the furthest enemy in range, dealing 300 Physical Damage to all enemies hit by it.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "The Ranger throws the boomerang at the furthest enemy in range, dealing 300 Physical Damage to all enemies hit by it."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Blade_Stage1_Default_Original.json
{
	"Name": "Blade",
	"Stage": 1,
	"Tier": 2,
	"Variation": "Original",
	"Type": "Normal",
	"CombatAffinity": "Air",
	"CombatClass": "Fighter",
	"DominantCombatAffinity": "Air",
	"DominantCombatClass": "Fighter",
	"Stats": {
		"MaxHealth": 0,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 65000,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 100,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 100,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 30,
		"CritAmplificationPercentage": 150,
		"OmegaPowerPercentage": 100,
		"AttackRangeUnits": 2,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 100,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 100,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 100,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [
		{
			"Name": "Blade Attack I",
			"Skills": [
				{
					"Name": "Attack",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 50
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Operation": "+",
									"Operands": [
										{
											"Stat": "AttackPhysicalDamage",
											"StatSource": "Sender"
										},
										{
											"Percentage": 20000,
											"Stat": "AttackSpeed",
											"StatSource": "Sender"
										}
									]
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Energy",
								"Expression": {
									"Stat": "AttackEnergyDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Stat": "AttackPureDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "Debuff",
								"Stat": "AttackSpeed",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Operation": "/",
									"Operands": [
										{
											"Stat": "AttackSpeed",
											"StatSource": "Receiver"
										},
										400
									]
								}
							}
						]
					}
				}
			]
		}
	],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"DisplayName": "Sylphid Blade",
	"DisplayDescription": "The Ranger deals bonus Physical Damage equal to 20% of their Attack Speed with each strike.\r\n\r\nAdditionally, each hit reduces the Target's Attack Speed by 0.25%.\r\n\r\nSylvan Blade: Gives Frost.\r\n\r\nMycotic Blade: Gives Frost and Slayer.",
	"Description": {
		"Format": "The Ranger deals bonus Physical Damage equal to {a}% of their Attack Speed with each strike.\r\n\r\nAdditionally, each hit reduces the Target's Attack Speed by 0.25%.\r\n\r\nSylvan Blade: Gives Frost.\r\n\r\nMycotic Blade: Gives Frost and Slayer.",
		"Parameters": {
			"a": {
				"ParameterPath": "AttackAbilities[0].Skills[0].EffectPackage.Effects[0].Expression.Operands[1].Percentage",
				"ValueMultiplier": 0.001
			}
		}
	},
	"DisplayDescriptionNormalized": "The Ranger deals bonus Physical Damage equal to 20% of their Attack Speed with each strike.\r\n\r\nAdditionally, each hit reduces the Target's Attack Speed by 0.25%.\r\n\r\nSylvan Blade: Gives Frost.\r\n\r\nMycotic Blade: Gives Frost and Slayer."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Maul_Stage2_Default_Original.json
{
	"Name": "Maul",
	"Stage": 2,
	"Tier": 5,
	"Variation": "Original",
	"Type": "Normal",
	"CombatAffinity": "Mud",
	"CombatClass": "Empath",
	"DominantCombatAffinity": "Earth",
	"DominantCombatClass": "Empath",
	"Stats": {
		"MaxHealth": 0,
		"StartingEnergy": 60000,
		"EnergyCost": 180000,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 200000,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 60,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 100,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 30,
		"CritAmplificationPercentage": 150,
		"OmegaPowerPercentage": 100,
		"AttackRangeUnits": 3,
		"OmegaRangeUnits": 3,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 100,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 100,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 100,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [
		{
			"Name": "Maul Attack II",
			"Skills": [
				{
					"Name": "Attack",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 50
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Energy",
								"Expression": {
									"Stat": "AttackEnergyDamage",
									"StatSource": "Sender"
								}
							},
							{
								"Type": "InstantDamage",
								"DamageType": "Pure",
								"Expression": {
									"Stat": "AttackPureDamage",
									"StatSource": "Sender"
								}
							}
						]
					}
				}
			]
		}
	],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [
		{
			"Name": "Willbreaker II",
			"TotalDurationMs": 1500,
			"Skills": [
				{
					"Name": "LIFT THE MAUL",
					"Targeting": {
						"Type": "CurrentFocus"
					},
					"Deployment": {
						"Type": "Direct",
						"PreDeploymentDelayPercentage": 75
					},
					"PercentageOfAbilityDuration": 100,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "NegativeState",
								"NegativeState": "Stun",
								"DurationMs": 2500
							}
						]
					}
				},
				{
					"Name": "AOE",
					"Targeting": {
						"Type": "InZone",
						"Group": "Enemy",
						"RadiusUnits": 20
					},
					"Deployment": {
						"Type": "Direct"
					},
					"PercentageOfAbilityDuration": 0,
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantDamage",
								"DamageType": "Physical",
								"Expression": {
									"Operation": "*",
									"Operands": [
										300000,
										{
											"Stat": "OmegaPowerPercentage",
											"StatSource": "Sender"
										}
									]
								}
							},
							{
								"Type": "Debuff",
								"Stat": "PhysicalResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							},
							{
								"Type": "Debuff",
								"Stat": "EnergyResist",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Abyssal Maul",
	"DisplayDescription": "The Ranger channels dark energy into their maul, delivering a crushing blow that Stuns the target for 2.5 seconds. The impact creates a shockwave, dealing 300*OP Physical Damage to all enemies within 20 radius.\r\n\r\nAdditionally, enemies hit by the shockwave have their Physical and Energy Resistances reduced  by 10.\r\n\r\nDreadmarsh Maul: Gives Mud and Revenant.",
	"Description": {
		"Format": "The Ranger channels dark energy into their maul, delivering a crushing blow that Stuns the target for {a} seconds. The impact creates a shockwave, dealing {b}*OP Physical Damage to all enemies within {d} radius.\r\n\r\nAdditionally, enemies hit by the shockwave have their Physical and Energy Resistances reduced  by {c}.\r\n\r\nDreadmarsh Maul: Gives Mud and Revenant.",
		"Parameters": {
			"a": {
				"ParameterPath": "OmegaAbilities[0].Skills[0].EffectPackage.Effects[0].DurationMs",
				"ValueMultiplier": 0.001
			},
			"b": {
				"ParameterPath": "OmegaAbilities[0].Skills[1].EffectPackage.Effects[0].Expression.Operands[0]",
				"ValueMultiplier": 0.001
			},
			"d": {
				"ParameterPath": "OmegaAbilities[0].Skills[1].Targeting.RadiusUnits"
			},
			"c": {
				"ParameterPath": "OmegaAbilities[0].Skills[1].EffectPackage.Effects[1].Expression"
			}
		}
	},
	"DisplayDescriptionNormalized": "The Ranger channels dark energy into their maul, delivering a crushing blow that Stuns the target for 2.5 seconds. The impact creates a shockwave, dealing 300*OP Physical Damage to all enemies within 20 radius.\r\n\r\nAdditionally, enemies hit by the shockwave have their Physical and Energy Resistances reduced  by 10.\r\n\r\nDreadmarsh Maul: Gives Mud and Revenant."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/LavaGauntlet_Amplifier_ConservationFlow_Default_Original.json
{
	"Name": "LavaGauntletConservationFlow",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"AmplifierForWeapon": {
		"Name": "LavaGauntlet",
		"Stage": 0,
		"Variation": "Original",
		"CombatAffinity": "Fire"
	},
	"Stats": {
		"MaxHealth": 400000,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 0,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"OmegaPowerPercentage": 0,
		"AttackRangeUnits": 0,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 0,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 0,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"InnateAbilities": [
		{
			"Name": "Conservation Flow",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Omega"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "Refund Energy",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "InstantEnergyGain",
								"Expression": {
									"Percentage": 35,
									"Stat": "EnergyCost",
									"StatSource": "Sender"
								}
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Conservation Flow",
	"DisplayDescription": "On Omega, refund 35% of Energy Cost.",
	"Description": {
		"Format": "On Omega, refund 35% of Energy Cost.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "On Omega, refund 35% of Energy Cost."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/LavaGauntlet_Amplifier_CumulativeIgnition_Default_Original.json
{
	"Name": "LavaGauntletCumulativeIgnition",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"AmplifierForWeapon": {
		"Name": "LavaGauntlet",
		"Stage": 0,
		"Variation": "Original",
		"CombatAffinity": "Fire"
	},
	"Stats": {
		"MaxHealth": 400000,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 0,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"OmegaPowerPercentage": 0,
		"AttackRangeUnits": 0,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 0,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 0,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"InnateAbilities": [
		{
			"Name": "CumulativeIgnition",
			"ActivationTrigger": {
				"TriggerType": "OnActivateXAbilities",
				"AbilityTypes": [
					"Omega"
				],
				"EveryX": true,
				"NumberOfAbilitiesActivated": 1
			},
			"TotalDurationMs": 0,
			"Skills": [
				{
					"Name": "CumulativeIgnition - Self Buff",
					"Deployment": {
						"Type": "Direct"
					},
					"Targeting": {
						"Type": "Self"
					},
					"EffectPackage": {
						"Effects": [
							{
								"Type": "Buff",
								"Stat": "AttackPhysicalDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPhysicalDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackEnergyDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackEnergyDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "AttackPureDamage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": {
									"Percentage": 10,
									"Stat": "AttackPureDamage",
									"StatSource": "Receiver",
									"StatEvaluationType": "Base"
								}
							},
							{
								"Type": "Buff",
								"Stat": "EnergyPiercingPercentage",
								"OverlapProcessType": "Stacking",
								"DurationMs": -1,
								"Expression": 10
							}
						]
					}
				}
			]
		}
	],
	"DisplayName": "Cumulative Ignition",
	"DisplayDescription": "On Omega, gain 10% Energy Piercing and 10 Attack Damage for the rest of the combat.",
	"Description": {
		"Format": "On Omega, gain 10% Energy Piercing and 10 Attack Damage for the rest of the combat.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "On Omega, gain 10% Energy Piercing and 10 Attack Damage for the rest of the combat."
}

=== owng25/arena-gauntlet-personal/json_data_copy/data/WeaponData/Amplifier/EmberBastion_Amplifier_HeatConversion_Default_Original.json
{
	"Name": "EmberBastionHeatConversion",
	"Stage": 0,
	"Tier": 0,
	"Variation": "Original",
	"Type": "Amplifier",
	"AmplifierForWeapon": {
		"Name": "EmberBastion",
		"Stage": 0,
		"Variation": "Original",
		"CombatAffinity": "Earth"
	},
	"Stats": {
		"MaxHealth": 700000,
		"StartingEnergy": 0,
		"EnergyCost": 0,
		"PhysicalResist": 0,
		"EnergyResist": 0,
		"TenacityPercentage": 0,
		"WillpowerPercentage": 0,
		"Grit": 0,
		"Resolve": 0,
		"AttackPhysicalDamage": 0,
		"AttackEnergyDamage": 0,
		"AttackPureDamage": 0,
		"AttackSpeed": 0,
		"MoveSpeedSubUnits": 0,
		"HitChancePercentage": 0,
		"AttackDodgeChancePercentage": 0,
		"CritChancePercentage": 0,
		"CritAmplificationPercentage": 0,
		"OmegaPowerPercentage": 0,
		"AttackRangeUnits": 0,
		"OmegaRangeUnits": 0,
		"HealthRegeneration": 0,
		"EnergyRegeneration": 0,
		"EnergyGainEfficiencyPercentage": 0,
		"OnActivationEnergy": 0,
		"VulnerabilityPercentage": 0,
		"EnergyPiercingPercentage": 0,
		"PhysicalPiercingPercentage": 0,
		"HealthGainEfficiencyPercentage": 0,
		"PhysicalVampPercentage": 0,
		"EnergyVampPercentage": 0,
		"PureVampPercentage": 0,
		"Thorns": 0,
		"StartingShield": 0,
		"CritReductionPercentage": 0
	},
	"AttackAbilitiesSelection": "Cycle",
	"AttackAbilities": [],
	"OmegaAbilitiesSelection": "Cycle",
	"OmegaAbilities": [],
	"InnateAbilities": [],
	"EffectsReplacements": [
		{
			"ID": "HeatConversion",
			"Type": "Buff",
			"Stat": "OmegaPowerPercentage",
			"OverlapProcessType": "Stacking",
			"DurationMs": -1,
			"Expression": 2
		}
	],
	"DisplayName": "Heat Conversion",
	"DisplayDescription": "During Omega, gain 2 Omega Power for each attack you receive.",
	"Description": {
		"Format": "During Omega, gain 2 Omega Power for each attack you receive.",
		"Parameters": {}
	},
	"DisplayDescriptionNormalized": "During Omega, gain 2 Omega Power for each attack you receive."
}
